### ISSUE TITLE
Notification: Transaction is started but vehicle do not consume energy

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1126]
The user starts a session and connects his vehicle.
The meter values are received in the backend but always with a 0 value meaning 'no consumption'
In that case, notify the user after 10 mins that his car is not charging at all.

**Comment by jerome-benoit** [comment]
QA: not tested but how is handled the use case: user schedule on his car a recharging start hours after he have plugged it?

**Comment by LucasBrazi06** [comment]
> QA: not tested but how is handled the use case: user schedule on his car a recharging start hours after he have plugged it?

Exactly! The user schedules a charge in the future and start the transaction right away!

**Comment by jerome-benoit** [comment]
> > QA: not tested but how is handled the use case: user schedule on his car a recharging start hours after he have plugged it?
> 
> Exactly! The user schedules a charge in the future and start the transaction right away!

It's not too difficult to simulate a started transaction that send MeterValues measurand Energy.Active.Import.Register set to zero with ev-simulator. Probably a tunable in the charging station template and a code switch to add while generating MeterValues.

**Comment by LucasBrazi06** [comment]
> It's not too difficult to simulate a started transaction that send MeterValues measurand Energy.Active.Import.Register set to zero with ev-simulator. Probably a tunable in the charging station template and a code switch to add while generating MeterValues.

Or you can plug your car with a plan in the future and start the transaction right away ;-)
Anyway these kind of test should be available in a Unit Test.

**Comment by jerome-benoit** [comment]
> > It's not too difficult to simulate a started transaction that send MeterValues measurand Energy.Active.Import.Register set to zero with ev-simulator. Probably a tunable in the charging station template and a code switch to add while generating MeterValues.
> 
> Or you can plug your car with a plan in the future and start the transaction right away ;-)
> Anyway these kind of tests should be available in a Unit Test.

Avoiding devs to have an electric car to validate that kind feature during their coding is always a plus ;) 
Especially if it's a matter of a few lines of code to permit it. 

Implementing time shift in unit tests is not easy with a real running service. 
Is the duration for the notification a tunable that can be set to one minute at a tenant level?

**Comment by LucasBrazi06** [comment]
> Is the duration for the notification a tunable that can be set to one minute at a tenant level?

It's the last 3 consumptions which depends on the OCPP meter interval value: if 60s, the last 3 mins.

**Comment by jerome-benoit** [comment]
> > Is the duration for the notification a tunable that can be set to one minute at a tenant level?
> 
> It's the last 3 consumptions which depends on the OCPP meter interval value: if 60s, the last 3 mins.

I've added a way to generate inactivity in ev-simulator: the metervalues sent can have a constant value defined in the charging station template. So if you start a transaction and the simulator send metervalues on the default measurand with a zero value, you generate inactivity.

So it can validated without requiring an electric vehicle by the dev ;)

**Comment by LucasBrazi06** [comment]
We can already simulate that in the unit tests.
The goal is to test with real vehicle here.

**Comment by jerome-benoit** [comment]
> We can already simulate that in the unit tests.
> The goal is to test with real vehicle here.
> 


There’s not added value to test that code path with a real vehicle or station here. As long as the unit test trigger inactivity the way described, the code path react the same and that’s enough.
So adding a unit test or testing with the simulator is enough.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> There’s not added value to test that code path with a real vehicle or station here. As long as the unit test trigger inactivity the way described, the code path react the same and that’s enough. So adding a unit test or testing with the simulator is enough.

I agree with you in a perfect world, but real tests may reveal new issues not covered in the Unit Tests like for instance the Unavailable status sent by Delta between the Finishing and Available. Different Charging Station models + different Cars may also lead to new problems.
We can also monitor the behavior in production if the end-users can run into this scenario.
Imho, Unit Tests and Real Tests are complementary.

**Comment by WillyLellouch** [comment]
If I understand correctly, for this issue I will need to plan a series of tests with different vehicles on different Charging Stations ?

**Comment by LucasBrazi06** [comment]
@OliveGerste Could provide a small test plan to Willy?

**Comment by WillyLellouch** [comment]
@OliveGerste ping ?

**Comment by WillyLellouch** [comment]
@OliveGerste Pinging you for that test plan. Thanks !

**Comment by OliveGerste** [comment]
@WillyLellouch I am sorry, but I do not think, that I have worked on this topic. 

@LucasBrazi06 I was assigned some time ago, but never did anything on this issue. Could you provide me some information about this?

**Comment by LucasBrazi06** [comment]
@OliveGerste I don't even think that we have implemented the notification here? :-)
The user should receive a notification if he managed to start a transaction and his car is not consuming energy after 10 mins.
???

**Comment by OliveGerste** [comment]
@LucasBrazi06 I think you are right.
I am about to start a new issue. Should I take care of this?
