### ISSUE TITLE
RESTful / Schema : Migrate Charging Station service endpoint

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1151]
- Start with 1 endpoint and make a PR and next 3 by 3 + PR
  - [x] Add Charging Station's REST service path in RESTful API
  - [x] Add the new RESTful endpoints in the OAS file
  - [x] Update the Unit Tests
- [x] Update the Front-end Http calls (make PR)
- [x] Update the Mobile App Http calls (after backend/front-end deployment in prod)
- [x] Update the Postman collection
- [x] Validate HTTP queries with JSon schemas in Charging Station service class (start with 1 endpoint and make a PR and next 3 by 3 + PR)
- [x] Remove Charging Station's security class

**Comment by Ninjeneer** [comment]
@LucasBrazi06 @jerome-benoit Before going any further, is this API definition good for you ? Thanks

METHOD | ACTION | REFACTORED ROUTE
-- | -- | --
GET | CHARGING_STATIONS | /chargingstations/
GET | CHARGING_STATION | /chargingstations/{id}
DELETE | CHARGING_STATION_DELETE | /chargingstations/{id}
POST | CHARGING_STATION_RESET | /chargingstations/{id}/reset
POST | CHARGING_STATION_CLEAR_CACHE | /chargingstations/{id}/cache/clear
GET | CHARGING_STATION_GET_CONFIGURATION | /chargingstations/{id}/configuration
PUT | CHARGING_STATION_CHANGE_CONFIGURATION | /chargingstations/{id}/configuration
POST | CHARGING_STATION_REMOTE_START_TRANSACTION | /chargingstations/{id}/remote/start
POST | CHARGING_STATION_REMOTE_STOP_TRANSACTION | /chargingstations/{id}/remote/stop
POST | CHARGING_STATION_UNLOCK_CONNECTOR | /chargingstations/{id}/connectors/{id}/unlock
POST | GENERATE_QR_CODE_FOR_CONNECTOR | /chargingstations/{id}/connectors/{id}/qrcode
POST | CHARGING_STATION_SET_CHARGING_PROFILE | /chargingstations/{id}/chargingprofile/set
POST | CHARGING_STATION_CLEAR_CHARGING_PROFILE | /chargingstations/{id}/chargingprofile/clear
GET | CHARGING_STATION_GET_COMPOSITE_SCHEDULE | /chargingstations/{id}/compositeschedule
GET | CHARGING_STATION_GET_DIAGNOSTICS | /chargingstations/{id}/diagnostics
PUT | CHARGING_STATION_UPDATE_FIRMWARE | /chargingstations/{id}/firmware
PUT | CHARGING_STATION_CHANGE_AVAILABILITY | /chargingstations/{id}/availability
GET | CHARGING_STATION_DOWNLOAD_QR_CODE_PDF | /chargingstations/{id}/qrcode/pdf
POST | CHARGING_STATION_REQUEST_OCPP_PARAMETERS | /chargingstations/{id}/ocppparameters
GET | CHARGING_STATIONS_OCPP_PARAMETERS | /chargingstations/{id}/ocppparameters
GET | CHARGING_STATIONS_OCPP_PARAMS_EXPORT | /chargingstations/{id}/ocppparameters/export
PUT | CHARGING_STATION_UPDATE_PARAMS | /chargingstations/{id}/params
PUT | CHARGING_STATION_LIMIT_POWER | /chargingstations/{id}/power/limit
GET | CHARGING_STATION_TRANSACTIONS | /chargingstations/{id}/transactions
GET | CHARGING_STATIONS_IN_ERROR | /chargingstations/inError
GET | CHARGING_STATIONS_EXPORT | /chargingstations/export
GET | FIRMWARE_DOWNLOAD | /chargingstations/firmware/{name}
GET | CHECK_SMART_CHARGING_CONNECTION | /chargingstations/smartcharging/check
GET | CHARGING_PROFILES | /chargingstations/profiles
DELETE | CHARGING_PROFILE_DELETE | /chargingstations/profiles/{id}
PUT | CHARGING_PROFILE_UPDATE | /chargingstations/profiles/{id}

**Comment by jerome-benoit** [comment]
Usually, URI are paths lowercased (not a big deal)

For POST, PUT requests, you do not need to have a parameter in the URI, everything goes in the body (JSON).

**Comment by LucasBrazi06** [comment]
@Ninjeneer Sounds good for me, few changes:
- /chargingstations/{id}/connectors/{id}/qrcode -> /chargingstations/{id}/connectors/{id}/qrcode (GET)
- /chargingstations/{id}/chargingprofile/set -> /chargingstations/{id}/chargingprofile (POST)
- /chargingstations/{id}/chargingprofile/clear -> /chargingstations/{id}/chargingprofile (DELETE)
- /chargingstations/{id}/qrcode/pdf -> /chargingstations/{id}/qrcode (GET)
- /chargingstations/{id}/params -> /chargingstations/{id}/parameters
- /chargingstations/inError -> /chargingstations/inerror
- /chargingstations/firmware/{name} -> /chargingstations/firmware/{id}
- /chargingstations/smartcharging/check -> /chargingstations/smartcharging/checkconnection

**Comment by Ninjeneer** [comment]
Documentation and routes are almost done. However I am facing an Express issue.

Let's say
**Route A** is /chargingstations/in-error
**Route B** is /chargingstations/:id

As Route **A** has a valid syntax to match Route **B**, the Express Router triggers both routes when calling Route **A**. 
I can't find anything related to this in the Router documentation, nor in forums. Did you ever faced this problem ?
And as Charging Stations IDs are their names, I can't use a regex filter here

**Comment by jerome-benoit** [comment]
> Documentation and routes are almost done. However I am facing an Express issue.
> 
> Let's say
> **Route A** is /chargingstations/in-error
> **Route B** is /chargingstations/:id
> 
> As Route **A** has a valid syntax to match Route **B**, the Express Router triggers both routes when calling Route **A**.
> I can't find anything related to this in the Router documentation, nor in forums. Did you ever faced this problem ?
> And as Charging Stations IDs are their names, I can't use a regex filter here

Add a subpath like /chargingstations/status/in-error. REST endpoints shall be idempotents, so  /chargingstations/:id and /chargingstations/in-error can't return different responses. 

Do the same for 
/chargingstations/export --> /chargingstations/action/export
and 
/chargingstations/profiles --> /chargingstations/smartcharging/profiles (and endpoints using it as a subpath)

**Comment by LucasBrazi06** [comment]
@Ninjeneer I let you check the checkboxes in the issue ;-)
