### ISSUE TITLE
Unit Test Tag testing (enable/disable)

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1260]
**User Create API :**

- [ ] A user created from the rest API must be flagged with issuer === true
- [ ] A user can be created with tag(s) marked with issuer === true or issuer === false

**User Read:**

- [ ] Create a user with a tag, then create x transaction(s) associated to this badge. The sessionCount property of each tag must be equal to the number of transactions.

**Tag delete:**

- [ ] A badge can be deleted if there is no session associated
- [ ] Deleting a badge already used means deactivating it.
- [ ] Check that a deleted badge of user A can be assigned to user B
- [ ] Check that a deactivated badge of user A cannot be assigned to user B
- [ ] Tag deactivation/activation
- [ ] A badge can be deactivated
- [ ] A badge can be reactivated
- [ ] A badge deactivated cannot be used to start/stop sessions.

**User delete:**

- [ ] Check that the deletion of a user with no session is completely removed from the DB
- [ ] Check that the deletion of a user with session is still present in the DB but with anonymized properties. Check that the never used badge have been deleted.

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Could you check if this issue is still relevant?

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Could you update this issue?
Thanks!
