### ISSUE TITLE
Charging Station Template : Factorize common OCPP configuration

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1310]
Create a common OCPP configuration section in the charging station's template which is valid for all charging stations.
Handle at least the heartbeat interval parameter in it and remove it from the config.json file in the backend.
Adjust the backend coding to read the params from the template to return to the charging station the right heartbeat interval during the BootNotification OCPP request.

**Comment by jerome-benoit** [comment]
It will not fit completely the reality of the OCPP parameters handling per vendor.  A template inheritance feature will fit almost completely the needs of having a way to factorise some configuration on a per vendor basis. A two level inheritance will be enough to have vendor agnostic configuration + vendor specific one. Or just a dedicated template that will be applied everywhere and a one level inheritance.

```
{
"id": "Common~Schneider";

} 
...
{
"id": "Schneider~Model";
"inheritFrom: "Common~Schneider";

} 
```

**Comment by LucasBrazi06** [comment]
Vendor specifics cannot be factorized as it is specific.
What we can factorize is the sections like OCPP Standard params or Technical sections like 22kW AC chargers with 2 connectors...

**Comment by jerome-benoit** [comment]
> Vendor specifics cannot be factorized as it is specific.
> What we can factorize is the sections like OCPP Standard params or Technical sections like 22kW AC chargers with 2 connectors...

With the one level inheritance mechanism described above added, it can.

**Comment by LucasBrazi06** [comment]
> > Vendor specifics cannot be factorized as it is specific.
> > What we can factorize is the sections like OCPP Standard params or Technical sections like 22kW AC chargers with 2 connectors...
> 
> With the one level inheritance mechanism described above added, it can.

Yes but on sections and not on vendor specifics.

**Comment by jerome-benoit** [comment]
> > > Vendor specifics cannot be factorized as it is specific.
> > > What we can factorize is the sections like OCPP Standard params or Technical sections like 22kW AC chargers with 2 connectors...
> > 
> > 
> > With the one level inheritance mechanism described above added, it can.
> 
> Yes but on sections and not on vendor specifics.

That time that's me that don't get why that restriction: you have a template "class" that can inherit from other same template "class", why the inheritance have to be partial? 

The inherited template must never be applied (flag probably needed) and really carefully written and checked regarding attributes like model. But it's in the *nix tradition to let the admins shoot themselves in the foot. And add syntax error only checking first then slowly add some consistency checks.
