### ISSUE TITLE
Charging Plans > Display Charging Plan Chart/List + Button to switch them in details section of Charging Plans list 

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1582]

**Comment by fcoutellier** [comment]
Need to review first the Charging Plan list (tab).

**Comment by LucasBrazi06** [comment]
![image](https://user-images.githubusercontent.com/25266945/95679684-c6ba4300-0bd4-11eb-8f8a-fff21bb734a8.png)
