### ISSUE TITLE
Make a release note with sentence in addition to the technical details

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1639]
Provide an end user explainable release note that will help following-up the progress between new releases.

![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/24a3d7d1-9194-4f74-b309-6dbb637e7e3e)

**Comment by jerome-benoit** [comment]
Also using `npm version`: https://docs.npmjs.com/cli/version in the process will automatically create a git tag, increment the version in package.json, etc.
