### ISSUE TITLE
Move Charging Station to another site area

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1702]
![image.png](https://images.zenhubusercontent.com/5e411e0517fa45e1af2c53aa/5027a45c-df49-44ea-bd80-628ae05c9261)

**Comment by LucasBrazi06** [comment]
This was not high prio for me.
We haven't discussed this task together (golden rule #2).
So you wasted your time on this.
The RESTful server was highly important.
Stick on it.
