### ISSUE TITLE
Charging Plan: Don't  take into account inactivity when Tx Profile charging plan is ongoing

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1742]

**Comment by LucasBrazi06** [comment]
We can have a short meeting if needed

**Comment by jerome-benoit** [comment]
QA: not tested.

**Comment by jerome-benoit** [comment]
> QA: not tested.

But is there anything to test yet? 

@OliveGerste: Have you already done a PR for that issue? 

I can easily add inactivity to transaction generator in ev-simulator.

**Comment by OliveGerste** [comment]
Should be testable already.
The inactivity is not taken into account when the limit of the charging profile is below 13 Amps per phase. 
Everything above is taken into account because it is real inactivity, when the car would be able to charge, but is not doing it.

**Comment by LucasBrazi06** [comment]
We should mock the charging station in our Unit Test for the charging profiles.
The goal of the ev-simulator is to provide load tests.

**Comment by jerome-benoit** [comment]
> We should mock the charging station in our Unit Test for the charging profiles.
> 
Adding a OCPP charging station server and client in the unit tests framework is not going to be quick. Writing information in DB to fake them is not enough to cover all use case.
Just like OCPI unit tests need an full OCPI server to cover all scenarii.
> The goal of the ev-simulator is to provide load tests.
> 

The goal of ev-simulator is to be a full blown charging stations simulator to ease features integration that need charging stations ;)
It’s going to be used for the PnC project to simulate not yet existing OCPP 1.6 stations with ISO 15118 extension for the January demo;
It’s going to be used to integrate OCPP 2.0.1 support for the same project and evaluate its smart charging feature;
etc.

It’s going to be one of the open source reference implementation to simulate PnC on station + vehicle …

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> Adding a OCPP charging station server and client in the unit tests framework is not going to be quick. Writing information in DB to fake them is not enough to cover all use case. Just like OCPI unit tests need an full OCPI server to cover all scenarii.

Ideally I totally agree but we don't have real Chargers/OCPI servers for now then we'll have to make our own mock servers and this will be possible now that we will have two teams next years and dedicated ressources working full time on this topic.

> It’s going to be one of the open source reference implementation to simulate PnC on station + vehicle …

OCA already has this kind of simulator, what's the purpose of redoing the wheel here and spending time you don't have ;-) ?

**Comment by jerome-benoit** [comment]
> It’s going to be one of the open source reference implementation to simulate PnC on station + vehicle …
> 
> OCA already has this kind of simulator, what's the purpose of redoing the wheel here and spending time you don't have ;-) ?
> 

The OCA test tools is not a simulator, just a test suite to evaluate level of conformance on OCPP commands. If you send it a start transaction, it just tell you if it’s conform or not. And it costs mini 6000$ and not free (as speech).

The only other free simulator available is the new motion one. And it has less feature than ours.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> The OCA test tools is not a simulator, just a test suite to evaluate level of conformance on OCPP commands. If you send it a start transaction, it just tell you if it’s conform or not. And it costs mini 6000$ and not free (as speech). The only other free simulator available is the new motion one. And it has less feature than ours.

Ok it makes sense now.
Then we should also provide step by step send of commands for the dev team to test a charging session like in Postman but using OCPP 1.6.

**Comment by jerome-benoit** [comment]
> The OCA test tools is not a simulator, just a test suite to evaluate level of conformance on OCPP commands. If you send it a start transaction, it just tell you if it’s conform or not. And it costs mini 6000$ and not free (as speech). The only other free simulator available is the new motion one. And it has less feature than ours.
> 
> Ok it makes sense now.
> Then we should also provide step by step send of commands for the dev team to test a charging session like in Postman but using OCPP 1.6.
> 


Its usage documentation is still missing but I’ve take a few minutes that morning during the dev meeting to explain how to use it. Tobias said that it will now avoid him to use Postman for metervalues sending by clicking regularly on play ;)

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> Its usage documentation is still missing but I’ve take a few minutes that morning during the dev meeting to explain how to use it. Tobias said that it will now avoid him to use Postman for metervalues sending by clicking regularly on play ;)

Perfect!
You'll need to demo it to me then now ;-).
But we need this play (step by step) scenario like in Postman.
