### ISSUE TITLE
Template: add supportFirmwareUpdate capabilities handling

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#1755]
Add new flag supportFirmwareUpdate in charging station's capabilities.
Hide upload firmware tab if not supported in the UI

**Comment by LucasBrazi06** [comment]
Go on this one

**Comment by LucasBrazi06** [comment]
@jerome-benoit required by Proviridis, to bee implemented asap.

**Comment by jerome-benoit** [comment]
> @jerome-benoit required by Proviridis, to be implemented asap.

What does they exactly require? 

The firmware update have been tested and works on all their charging stations in their tenant: 

+ DELTA: tested and working;
+ Keba: tested and working. 

And the same goes for all the charging station model used on SLF tenants (Webasto, Ebee, Legrand, Schneider, Mennekes, etc.) and some of the stations on the test charger tenant. Implementing that feature in the template code will just display the very same on the dashboard. 

So if they have issue at using that feature with the current UI, that will not change anything. 
And improving the firmware UI update tab user experience is another topic.  

An understanding of what they exactly expect regarding the firmware upgrade to make the correct choice at firmware update issue priority for customers.

**Comment by LucasBrazi06** [comment]
When you say tested what does it mean?
Should they provide an HTTP of FTP server for this?
Don't forget that the target is to provide a firmware management in the end with only versions that we have tested stored in our DB/Cloud.

**Comment by jerome-benoit** [comment]
> When you say tested what does it mean?

That we have: 

+ uploaded firmware files to the DB for each model used on SLF tenants; 
+ done firmware upgrades by using HTTP with the reverse proxy at Mougins (HTTPS is not supported by most of the vendors). 

All firmware upgrade on all charging stations on the SLF tenants have been done that way since months. And have worked flawlessly with rare exceptions (Webasto latest firmware is not signed properly, ATESS requires firmware class change).

But I know how to use the UI: the URL to put in to get the correct file, etc. 
I would not say that the current UI is intuitive for people that do not have that knowledge. 
   
> Should they provide an HTTP of FTP server for this?

No. We can deliver firmware file through HTTP(S) only.

> Don't forget that the target is to provide a firmware management in the end with only versions that we have tested stored in our DB/Cloud.

I know. I just want to be sure that issue at making firmware upgrade works by other than me is well understood: the current UI is not intuitive enough. 
And for specific customers like charging station installer/maintainer, charging station vendors, etc. still allow them to test specific version OCPP firmware upgrade on their tenant. That can be coupled to the enablement of all charging charging tunables edition for example if a customer choose to out a station from the official support for whatever reason.

**Comment by LucasBrazi06** [comment]
First, I will put Caroline on this topic to build what is missing to make it user friendly.
Next, in parallel we need to disable this feature in prod unless we have this user friendly UI, thus the flag to implement.
Finally, we need a way to test it in QA by providing QA-only templates and why not a simple UI in the tenant management to update the json template right away and flag it as QA (will not be overridden by new version).

**Comment by jerome-benoit** [comment]
> Next, in parallel we need to disable this feature in prod unless we have this user friendly UI, thus the flag to implement.

If the flag just state in template that firmware upgrade have been tested and works to display the tab, that will not change anything. 
To avoid the extra work to flag a tunable on each station with a false and after a true on a huge list of station templates, commenting out the firmware tab code on the UI is suffisant.
As a learning exercice, Caroline can also add the code the handle the supportFirmwareUpdate tunable server side. That way, she will have to implement fully a feature, which more interesting.

**Comment by LucasBrazi06** [comment]
> If the flag just state in template that firmware upgrade have been tested and works to display the tab, that will not change anything.

Yes.

> To avoid the extra work to flag a tunable on each station with a false and after a true on a huge list of station templates, commenting out the firmware tab code on the UI is suffisant.

Yes, we can do that only in production if this is doable in the meantime.

> As a learning exercice, Caroline can also add the code the handle the supportFirmwareUpdate tunable server side. That way, she will have to implement fully a feature, which more interesting.

Yes, why not, but I think she has to meet Willy first too have a short OCPP introduction.
And then I will try to find her a small task so she can play/test the framework.
After we can define the steps to implement what we want.
