### ISSUE TITLE
Template: add a warning when a template will override an already defined one

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#1757]

**Comment by LucasBrazi06** [comment]
I don't get that one

**Comment by jerome-benoit** [comment]
It's to avoid the error I've made to handle Ebee Master/Slave and Ebee standalone. 
I do not think it's a priority, it would be just nice to have.

**Comment by LucasBrazi06** [comment]
> It's to avoid the error I've made to handle Ebee Master/Slave and Ebee standalone.
> I do not think it's a priority, it would be just nice to have.

Is it when you have two same templates matching the same charging station right?

**Comment by jerome-benoit** [comment]
> > It's to avoid the error I've made to handle Ebee Master/Slave and Ebee standalone.
> > I do not think it's a priority, it would be just nice to have.
> 
> Is it when you have two same templates matching the same charging station right?

Yes. Warn admin for such template configuration mistake would be nice before applying.

**Comment by LucasBrazi06** [comment]
> > Is it when you have two same templates matching the same charging station right?
> 
> Yes. Warn admin for such template configuration mistake would be nice before applying.

Ok got it.
Thanks!
