### ISSUE TITLE
Locking and Self-healing: make the migration locking self-healed after crash

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#1760]
Do not block all migrations because of a failure in only one

**Comment by LucasBrazi06** [comment]
Migration tasks cannot be parallelized every async ones so we'll keep the lock for the whole migration

**Comment by jerome-benoit** [comment]
That has nothing to do concurrency, it's about self-healing with automatic batch server restart in case of one migration task that have caused the crash when multiples migration tasks must be run: the other migration tasks except the one that have crashed are executed. 

That's one of the BCP (Best Current Practice) for the mutex locking primitive usage.

**Comment by LucasBrazi06** [comment]
No, if they are dependent of each others you cannot do that.

**Comment by jerome-benoit** [comment]
> No, if they are dependent of each others you cannot do that.

The mutex locking on migration is fact not needed at all: one node.js process on one server and just cause extra work because of check of deadlock in DB. The task execution ordering already reflect their dependencies    

So making the locking optional with a method boolean parameter on migrate() will solve the self-healing issue after one migration crash.

**Comment by LucasBrazi06** [comment]
> > No, if they are dependent of each others you cannot do that.
> 
> The mutex locking on migration is fact not needed at all: one node.js process on one server and just cause extra work because of check of deadlock in DB. The task execution ordering already reflect their dependencies
> 
> So making the locking optional with a method boolean parameter on migrate() will solve the self-healing issue after one migration crash.

I still don't get what you mean.
There will be several instances of the batch server in the future in other to scale with the scheduled tasks and only one server can perform the migration of the DB with ordered and dependant tasks so the lock is definitively needed!!!

**Comment by jerome-benoit** [comment]
> > > No, if they are dependent of each others you cannot do that.
> > 
> > 
> > The mutex locking on migration is fact not needed at all: one node.js process on one server and just cause extra work because of check of deadlock in DB. The task execution ordering already reflect their dependencies
> > So making the locking optional with a method boolean parameter on migrate() will solve the self-healing issue after one migration crash.
> 
> I still don't get what you mean.
> There will be several instances of the batch server in the future in other to scale with the scheduled tasks and only one server can perform the migration of the DB with ordered and dependant tasks so the lock is definitively needed!!!

Sure but if it's not needed like with the current setup on SCP or AWS, just allow to disable the locking on migration tasks execution. So even after a crash on the batch server, the migration tasks continue after the server restart. It's just a like tunable on Migration configuration, defaulting to true but that can be disabled when not necessary. That will have help you for the massive recalculation for example. 

The self-healing of migration tasks with several servers and locking will need more thought and work, but for simple setup, the such a tunable can help. 

I hope I've make myself clear enough.

**Comment by LucasBrazi06** [comment]
Ok I got it now, thanks for the explanations!
We can also link the Lock ID stored in the DB with the server IP or Name so if it crashes, it can reacquire the same lock again.
What do you think?

**Comment by jerome-benoit** [comment]
> Ok I got it now, thanks for the explanations!
> We can also link the Lock ID stored in the DB with the server IP or Name so if it crashes, it can reacquire the same lock again.
> What do you think?

To handle the self-healing with locking and several servers? 

The lock cleanup method that was run at startup before was doing exactly that but not fine grained at lock type level, it was removing all locks put by the crashed app. The SCP application name is unique and do not change so that it will work, but on AWS, the hostname and IP change all the time, we have to find something unique and persistent that identify containers on Fargate ...

**Comment by stefania-santimbrean** [comment]
Note about database locks and migration of sensitive data:

- for migration of sensitive data a database lock is acquired
- if the server crashes and the migration is not completed, the lock is not released
- but the migration has to be resumed and for that to happen, the database lock have to be released

To solve this problem:
- at server start, all database locks with key 'migrate-sensitive-data' are deleted

@jerome-benoit please add any other info you think relevant about this topic
