### ISSUE TITLE
Statistics > Cost per user doesn't change

### ISSUE THREAD

**Issue by mariansalceda** [sap-labs-france/ev-dashboard#1781]
The cost per user should change according to the user's individual consumption like the other tabs do. but the pricing tab shows the price for all users.

![image.png](https://images.zenhubusercontent.com/5e5d2a5f0de74343d65e223a/f2af7412-ac03-44f1-b1a2-5f3539a27dec)

**Comment by OliveGerste** [comment]
Small addition: The costs are not displayed correctly, only when the selected user does not have any sessions.
