### ISSUE TITLE
Logs > Server Actions Filter: Keep the checked records when filtering

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1838]
When action pop-up filter is displayed and you filter + select the actions, if you change the filter, the selection is lost.
The selection should be kept between two filtering:
Also the Seach field should receive the focus
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/6a4fc750-f2bd-4acb-b2c2-a7449c054d50)

**Comment by jerome-benoit** [comment]
+ a button to permit the reset the actions selection.

**Comment by jerome-benoit** [comment]
May I ask for a priority bump on that one? 
It really makes the operational daily log digging task painful and time consuming to have re-select all actions just because you've missed some.

**Comment by LucasBrazi06** [comment]
> May I ask for a priority bump on that one?
> It really makes the operational daily log digging task painful and time consuming to have to re-select all actions just because you've missed some.

Done ;)
