### ISSUE TITLE
Security: Add an operator like role 

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#1871]
An operator shall be able to: 

- Read charging stations list;
- Read charging stations informations and configuration details, write the number of phases configuration;
- Read, write site and site area;
- Read, write charging station connexion token; 
- Read logs 

And no access to anything else. 

Target is technicians doing charging station installation and troubleshooting.

**Comment by LucasBrazi06** [comment]
This role is close to the Site Admin role.

**Comment by jerome-benoit** [comment]
> This role is close to the Site Admin role.

Probably but it is not tied to a list of sites, its scope is at the tenant level.

**Comment by LucasBrazi06** [comment]
> > This role is close to the Site Admin role.
> 
> Probably but it is not tied to a list of sites, its scope is at the tenant level.

Ok
