### ISSUE TITLE
Smart Charging: handle the Car in Smart Charging

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1889]

**Comment by WillyLellouch** [comment]
Could I have a Use Case for this ?

**Comment by LucasBrazi06** [comment]
> Could I have a Use Case for this ?

You can contact the developper for the use case.
Thanks.

**Comment by OliveGerste** [comment]
@WillyLellouch 
The goal is to set the limit of the charging station according the capabilities of the car.
So if a car is able to charge 16 Amps 3 Phase the limit should be set to 16 Amps per phase. 
If the car is able to charge 31 Amps single phase, the limit should be set to 31 Amps per phase.
