### ISSUE TITLE
Billing: Write documentations for: onboarding new tenant / end-user

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1895]

**Comment by Ninjeneer** [comment]
@LucasBrazi06 Is there any format/template I should use to write this ?

**Comment by LucasBrazi06** [comment]
@Ninjeneer You can check the Sharepoint folder and pickup a documentation already released for end-user.
You can also ask Gerald if he has a template, he wrote many of them already.

**Comment by Ninjeneer** [comment]
[SAP_E-Mobility_Onboarding_Billing_V1.01.pdf](https://github.com/LucasBrazi06/ev-dashboard/files/5473841/SAP_E-Mobility_Onboarding_Billing_V1.01.pdf)
