### ISSUE TITLE
Export in general are limited to 100 lines.

### ISSUE THREAD

**Issue by fcoutellier** [sap-labs-france/ev-dashboard#1917]
Export in general (log, session, charging stations) are limited which is in some cases less than what it is shown in the UI (cf. log entires).

Get rid of this limitation for all screen except for logs where the exported lines must match to the filter.

**Comment by LucasBrazi06** [comment]
Export logs have to be limited somehow, you cannot export several millions of lines or you will kill the server.
Moreover, there is a general issue with export at server side: the exported files should be returned by chunks and DB read with pagination active (200 records).

**Comment by fcoutellier** [comment]
I agree, but you should at least be able to export what it is displayed in the screen which is a bit more than 100 lines and should not be enough to trigger performance issue.

**Comment by fcoutellier** [comment]
@LucasBrazi06 : I think that you are on it right?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 : I think that you are on it right?

@fcoutellier yes and moved to QA

**Comment by LucasBrazi06** [comment]
Fixed
