### ISSUE TITLE
Charging Station - Provide human being name

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1925]
Provide an editable name for a charging station ID and:
- Display it in all lists (meaning lookup with charging station collections in all the DB storages)
- Use it in filtering and search
- Add it in export
- Ensure performance is kept acceptable
- Use it in SAP Analytics? Check in all the app...

**Comment by LucasBrazi06** [comment]
> If that means that we can have two identifiers for humans and the same object, to avoid confusion for operators that might use the charging station admin interface, the two ids if different should be displayed at least in the charging station IHM details.
> And maybe also provide a way to sync the two ids when possible.

No we have only one ID and a name which can have dups.

**Comment by jerome-benoit** [comment]
> > If that means that we can have two identifiers for humans and the same object, to avoid confusion for operators that might use the charging station admin interface, the two ids if different should be displayed at least in the charging station IHM details.
> > And maybe also provide a way to sync the two ids when possible.
> 
> No we have only one ID and a name which can have dups.

That's what I mean by identifier for human: users can have one name on the dashboard and an other on the charging station. In the case they are different, both should be displayed on the details, so operators can check if they are logged on the right charging station web interface to troubleshoot.
