### ISSUE TITLE
Performances: Log REST/OCPP/MongoDB API performances, data volumes + Traces of calls

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1928]
Goal is to track the performances and data volumes and we can identify from a REST call how many times the DB is called and same for OCPP to improve the performances.

**Comment by jerome-benoit** [comment]
> Goal is to track the performances and data volumes and we can identify from a REST call how many times the DB is called and same for OCPP to improve the performances.
> 
Do not forget that will already have Dynatrace doing it. That kind of report can be already done by it after some reports configuration.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
> Do not forget that will already have Dynatrace doing it. That kind of report can be already done by it after some reports configuration.

We don't have currently Dynatrace deployed on all the platforms, we depend on a third party tool and it's not free of use.
I think we can really have, with a minimum of effort on our side, our own metrics in thee DB that really fits our need (linking OCPP calls with DB ones grouped under each call, same for REST calls) and plug on top any tools to track and analyze them.
We have also Kibana but as Dynatrace, it's too generic and overkilling tools, we need also to be trained...
