### ISSUE TITLE
Smart Charging: When Static Limitation is changed, check that the sum of all Chargers won't go beyond the Site Area limitation

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1944]

**Comment by OliveGerste** [comment]
@LucasBrazi06 
In my understanding the staitc limitaion can just be changed if the charging station is excluded from smart charging right?
And if the cs is excluded from smart charging the siteArea limitation is already adjusted.
Could you explain a bit more what is needed to be done here?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06
> In my understanding the staitc limitaion can just be changed if the charging station is excluded from smart charging right?
> And if the cs is excluded from smart charging the siteArea limitation is already adjusted.
> Could you explain a bit more what is needed to be done here?

It's when the smart charging is not active, you can enter a site area limitation and play with the static limitation go over the site area limit.
You can check Hanno's Wallbox in charge at home tenant (slfcah).
Goal is to display an error message when trying to apply the static limitation when it goes beyond the SA limit. Error has to be returned by the backend and only if the organization is active and site area limit is positive.

**Comment by OliveGerste** [comment]
Okay I got your point.
What is about the case when the sum of the limit of the charging stations is beyond the site area limitation by default, without changing the static limitation?

When you change the the static limitation once you will not be able to change it back to default, without changing other charging stations limit right?

**Comment by LucasBrazi06** [comment]
> Okay I got your point.
> What is about the case when the sum of the limit of the charging stations is beyond the site area limitation by default, without changing the static limitation?
> 
> When you change the the static limitation once you will not be able to change it back to default, without changing other charging stations limit right?

Either you can go beyond the SA limit by changing one CS limit or you'll have to raise the SA max limit.

Ideally we thought of having a set of sliders in the SA to control the limit of each CS (SA power can also be evenly dispatched to each CS limit automatically) and apply these limits to all CS at once but we are lacking of time and it's less prio ;-)
