### ISSUE TITLE
Charging Profile: Pass the number of phases in the profile

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#1965]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/2dc3d523-bdc6-461d-86a9-f43a4c43e517)

**Comment by LucasBrazi06** [comment]
@jerome-benoit Double check if it's still necessary and eventually close the issue

**Comment by jerome-benoit** [comment]
It's still necessary for the stations that only support charging profiles in Watts. 
And if the amperage per phase limit in profile is not properly calculated with the number of really used phases, but it's very unlikely with the optimizer:
  + you want to use 16A total max and your car is tri-phased: limit per phase must be 16/3 in the profile
  + you want to use 16A total max and you car is mono-phased: limit per phase must be 16 in the profil

Are the use cases clear enough?
