### ISSUE TITLE
Smart Charging: Sticky Smart Charging implementation

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2042]
When receiving Meter Values (2), set the charging plan (1) 10% above the current consumption (should not go beyond the max connector's power.)

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/48ff66d9-ea78-439e-b6bd-3d1266c9b295)

**Comment by WillyLellouch** [comment]
Could I have a more detailed use case for this one ? Thanks.

**Comment by LucasBrazi06** [comment]
> Could I have a more detailed use case for this one ? Thanks.
You can contact the developer.

**Comment by OliveGerste** [comment]
@WillyLellouch 
The goal is to free capacity of a charging station which is not used from the car.
So if the limit is set to 150kW but the car only charges at 40kW. We set the limit of the station to 40kW with a configured buffer (currently 20%).
It is adjusted every time the optimizer runs.
