### ISSUE TITLE
Smart Charging : DST time change impacting charging plan

### ISSUE THREAD

**Issue by yannpub** [sap-labs-france/ev-dashboard#2043]
Since we went back to winter time, the charging plan is still showing proper hours, however the charging starts _one hour ahead_.

**Expected Behaviour** : Charging starts at 11pm
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/21988643/97271280-a7f0b900-1830-11eb-8b19-b0bbec5f54ac.png">

**What's happening** : Charging starts at 10pm
<img width="373" alt="image" src="https://user-images.githubusercontent.com/21988643/97271519-f2723580-1830-11eb-8e0b-27190245ccd2.png">
The charging station is obviously in supervised mode, and its hour is correct:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/21988643/97271675-2188a700-1831-11eb-8c2b-f4a18b88a421.png">

**Comment by LucasBrazi06** [comment]
@yannpub In english please ;-)

**Comment by jerome-benoit** [comment]
@yannpub 

1. Is it reproducible? Have you retried?  
2. Is yes, could you then set you station timezone to UTC and see if it happens again? 

And give us your feedbacks here. 

Thanks.

**Comment by yannpub** [comment]
I restarted a session today, and charging restarted at 22:00 and not 23:00 like in my charging plan.
I stopped the session, and changed time zone on the charging session:
![image](https://user-images.githubusercontent.com/21988643/97500137-5b5fc780-196f-11eb-9744-e5b09ecc5b61.png)
![image](https://user-images.githubusercontent.com/21988643/97500145-6286d580-196f-11eb-96ca-2d84a400d903.png)
![image](https://user-images.githubusercontent.com/21988643/97500160-6adf1080-196f-11eb-821a-0f4419e91fa2.png)

I waited 10 minutes and restarted a session:
![image](https://user-images.githubusercontent.com/21988643/97500196-79c5c300-196f-11eb-8224-fb9ae76ca010.png)
and the charging started immediately, instead of waiting until 23:00
![image](https://user-images.githubusercontent.com/21988643/97500297-a1b52680-196f-11eb-977a-a09969398269.png)

**Comment by jerome-benoit** [comment]
Really set UTC in the timezone, nor Universal or etc/UTC, I still see Europe/Paris in your settings. 
And reboot your station after the timezone change and check that the change is still here.

**Comment by jerome-benoit** [comment]
I've made the timezone change.

**Comment by yannpub** [comment]
The station was still on 'Universal' this morning. I just changed it to UTC and rebooted.
![image](https://user-images.githubusercontent.com/21988643/97537856-c33dfe80-19bf-11eb-918a-fb42d5a3ed5c.png)

Will give it a try this evening again.

**Comment by jerome-benoit** [comment]
You're the only one to have that issue. We have several users having the same Wallbox with similar recurring charging profile and none of them have that issue. 
So to report it to Schneider, you will have to send us the charging station report.

**Comment by LucasBrazi06** [comment]
> You're the only one to have that issue. We have several users having the same Wallbox with similar recurring charging profile and none of them have that issue.

It would be actually good to double check with other colleagues (Florent...)

**Comment by jerome-benoit** [comment]
+ Set timezone to UTC -> KO
+ Factory reset with timezone to Europe/Paris -> KO

**Comment by yannpub** [comment]
Changing **start date** for the charging plan (not changing anything else) from Sept 11 (**Before DST** change) to November 4th (**After DST** change) worked.

**_Old:_**
![image](https://user-images.githubusercontent.com/21988643/98217528-e847e980-1f4a-11eb-9be6-71027074be5e.png)

**_New:_**
![image](https://user-images.githubusercontent.com/21988643/98217548-f0a02480-1f4a-11eb-9c25-348a212588b2.png)

**Comment by yannpub** [comment]
**_Reproduce issue:_**

Changing start date for the charging plan (not changing anything else) from November 4 (**After** DST change) to September 1st (**before** DST change) reproduced the initial bug: the car started charging at 22:00 and not 23:00.

**_Old:_**
See previous post

**_New:_**
image
![image](https://user-images.githubusercontent.com/21988643/98340465-af247d80-200d-11eb-8d9d-cc157dfc8bfb.png)

**Comment by jerome-benoit** [comment]
The issue is on the charging station then.

**Comment by yannpub** [comment]
I don't think that the charging station is keeping a Daylight Saving Time calendar. It is getting its time either manually, either through NTP or through the supersivion. So I think the charging station is 'DST' agnostic.

Therefore, the backend should send the time according to **the current day**, and not according to the _profile start date_.

**Comment by jerome-benoit** [comment]
> I don't think that the charging station is keeping a Daylight Saving Time calendar. It is getting its time either manually, either through NTP or through the supervision. So I think the charging station is 'DST' agnostic.

That's not the case on Schneider ones.

> 
> Therefore, the backend should send the time according to **the current day**, and not according to the _profile start date_.

As I said, it's already the case: all dates in charging profiles are relative to UTC and all schedules are relative to that date in seconds. And in recurring profile, the exact day is not taken into account and the start hour is relative to UTC. 
Unless we have a bug at putting the start date to UTC (which does not seem to be the case), the issue is at handling the start date on the charging station properly.

**Comment by yannpub** [comment]
> As I said, it's already the case: all dates in charging profiles are relative to UTC and all schedules are relative to that date in seconds. And in recurring profile, the exact day is not taken into account and the start hour is relative to UTC.

When I look at the logs, for the same charging profile (32A from 11pm to 7am), the hours is not the same depending on the profile start date:

**When setting a start date before DST change:**
 "chargingProfileKind": "Recurring",
                        "recurrencyKind": "Daily",
                        "chargingSchedule": {
                              "duration": 86400,
                              "startSchedule": "2020-08-31T**22**:00:00.000Z",
                              "chargingRateUnit": "A",
                              "chargingSchedulePeriod": [
                                    {
                                          "startPeriod": 0,
                                          "limit": 32
                                    },
                                    {
                                          "startPeriod": 25200,
                                          "limit": 0
                                    },
                                    {
                                          "startPeriod": 82800,
                                          "limit": 32

**When setting a start date after DST change:**
                       "chargingProfileKind": "Recurring",
                        "recurrencyKind": "Daily",
                        "chargingSchedule": {
                              "duration": 86400,
                              "startSchedule": "2020-11-03T**23**:00:00.000Z",
                              "chargingRateUnit": "A",
                              "chargingSchedulePeriod": [
                                    {
                                          "startPeriod": 0,
                                          "limit": 32
                                    },
                                    {
                                          "startPeriod": 25200,
                                          "limit": 0
                                    },
                                    {
                                          "startPeriod": 82800,
                                          "limit": 32

**Comment by jerome-benoit** [comment]
You're right, the UTC time calculation is wrong on the server at profile payload generation given the date inputed on the dashboard. 

Since I'm vacation, I add @OliveGerste who is the charging profiles code master to the issue :)

**Comment by jerome-benoit** [comment]
Update: 

+ Issue is definitely on the Schneider firmware side;
+ Fix expected in the next firmware versiom.

**Comment by jerome-benoit** [comment]
@yannpub: Schneider have released a new firmware version. Could you please install it to see if it fix that issue? 

Thanks.

**Comment by yannpub** [comment]
As expected with the DST change, again the start of the charging session did not start appropriately. Now that we changed from UTC+1 to UTC +2, previous charging profile, which was to start at 23:00 now starts at 24:00.
The issue is still that the charging profile is based on the daily planning start date and not on the actual date.

Issue is with Charging profile:
Start time : 23:00 winter time (daily planning start date November 1st 2020), meaning 22:00UTC. France time zone is UTC +1.
--> local start time 23:00 during winter
/|\ Change of time with DST
France time zone becomes UTC+2 --> start time still 22:00UTC --> local start time becomes 24:00 which is not what is expected from an user perpective. Charging profile has to be DST agnostic, high peak tarifs do not change with DST

![image](https://user-images.githubusercontent.com/21988643/113389257-0138b780-9390-11eb-8ac4-f362bafccd59.png)

**Comment by jerome-benoit** [comment]
The charging profile date format is timezone agnostic in the OCPP spec and we implement it correctly in e-Mobility. 
The issue is that the Schneider firmware is does not handle it correctly given the timezone defined on the charging station.

**Comment by yannpub** [comment]
The problem is that the usage of the 'start date' in the charging profile is a non-sense from an user prospective, and especially for a recurring daily profile.
Just send the time based on the day we are, and that will be correct independantly of any time change. What is the added-value of sending a time calculated in winter time when it is summer time? and vice-versa? none.
