### ISSUE TITLE
Email Server: Investigate why Email server is not working all the time

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2090]
The email backup at 1&1 is no longer available (check with Gerald).

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/ed10e0eb-f4c4-424d-981f-d71a132e0a10)

**Comment by jerome-benoit** [comment]
We incorrectly trigger SMTP backup usage when ev-server send an email on no more existing email account. 
The workaround is either:
+ to delete the matching account on the tenant. 
+ to disable notifications on the tenant matching account. 

SMTP backup have been moved to AWS as part of that issue.

**Comment by LucasBrazi06** [comment]
> We incorrectly trigger SMTP backup usage when ev-server send an email on no more existing email account.
> The workaround until SMTP error handling is added to ev-server is either:
> 
> * to delete the matching account on the tenant.
> * to disable notifications on the tenant matching account.
> 
> SMTP backup have been moved to AWS as part of that issue.

If we can detect this at 100%, we can mark the user as inactive and disable all the notifications in his profile.

**Comment by jerome-benoit** [comment]
> > We incorrectly trigger SMTP backup usage when ev-server send an email on no more existing email account.
> > The workaround until SMTP error handling is added to ev-server is either:
> > 
> > * to delete the matching account on the tenant.
> > * to disable notifications on the tenant matching account.
> > 
> > SMTP backup have been moved to AWS as part of that issue.
> 
> If we can detect this at 100%, we can mark the user as inactive and disable all the notifications in his profile.

Maybe not the user, we can't say if the user is inactive because of SMTP error 5.1.1, he can just have moved his email addresses. 
But you can for sure detect if the error is repeated and then mark the email as invalid, no more sending email notification and warn the user with a new decicated push notification for invalid email.

**Comment by LucasBrazi06** [comment]
Ok, then it's a dedicated dev, new issue.

**Comment by jerome-benoit** [comment]
> Ok, then it's a dedicated dev, new issue.

Yes, I will only add SMTP error handling to solve that issue and use it to trigger or not SMTP backup usage.

**Comment by LucasBrazi06** [comment]
@jerome-benoit All your PRs are 'draft' except the mobile one, is it on purpose?

**Comment by jerome-benoit** [comment]
> @jerome-benoit All your PRs are 'draft' except the mobile one, is it on purpose?

Yes, the mobile app needs handle both notification name first. And deployed in production. 

Once done. The renaming will have no impact on it. 

The rest is going to be deployed side by side at the same time.

**Comment by LucasBrazi06** [comment]
> > @jerome-benoit All your PRs are 'draft' except the mobile one, is it on purpose?
> 
> Yes, the mobile app needs to handle both notification name first. And deployed in production.
> 
> Once done, the renaming will have no impact on it.
> 
> The rest is going to be deployed side by side at the same time.

Both solution should work we should not wait.
Just provide a comment to remove it after deployment.

**Comment by jerome-benoit** [comment]
> > > @jerome-benoit All your PRs are 'draft' except the mobile one, is it on purpose?
> > 
> > 
> > Yes, the mobile app needs to handle both notification name first. And deployed in production.
> > Once done, the renaming will have no impact on it.
> > The rest is going to be deployed side by side at the same time.
> 
> Both solution should work we should not wait.
> Just provide a comment to remove it after deployment.

I can duplicate notification code server side and sent them with both name. The mobile app will only no need to be updated.

**Comment by LucasBrazi06** [comment]
> I can duplicate notification code server side and sent them with both name. The mobile app no need to be updated.

If you send twice the notif, the user will receive 2 notifs on his mobile app and if you touch one you will navigate to the app and here the processing will happen.
I just checked the mobile code and there is no actions related to this notif, it only opens the app.
So the new notif will do the same and unknown notif IDs are currently ignored.
So you can deploy this backend version.
You see now how much it can be complicated to handle a simple renaming of a variable.
