### ISSUE TITLE
Charging Stations > Templates: Apply template to fill in all Charging Station/Connector specs

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2112]
Goal is to have access to charging station total power in the UI with no further processing in Charge Point.
Same for accessing Amps, Voltage, Power in connectors and wherever necessary.
Goal is to minimize access to Utils methods (getChargingStationPower, getChargingStationVoltage, getChargingStationCurrentType, getChargingStationAmperage...)

**Comment by jerome-benoit** [comment]
Regarding charging stations specifications in template and in general, the more important thing for now is to properly handle AC/DC ones: 
+ Keep AC specs as electrical inputs and assume there are the same on AC ones. 
+ Compute correctly DC electrical outputs from AC inputs: 
    + Use conversion efficiency; 
    + AC and AC/DC charging stations seem to use the same AC power units (the overall power is shared) -> the splitting of current type at the charge point level does not fit, the inverter part doing the current conversion inside the AC charge point instead of being apart; 
    + AC and AC/DC charging stations seem to calculate electrical specs on a 400V(RMS) basis ->  the current max static limitation calculation is buggy and probably also the charging profiles. If that's not the case for charging profiles, untangling static limitation from charging profiles limitation value is a pre-requisite to use 400V + efficiency in the computation for AC/DC

@OliveGerste: how to you compute the charging profiles limitation value on AC/DC? Do you assume that the limitation is applied to the AC power units always for AC/DC?

**Comment by LucasBrazi06** [comment]
> Compute correctly DC electrical outputs from AC inputs:
> * Use conversion efficiency;

This is the contrary, if we say that the charger delivers 150kW DC then the AC part will consume more, then it is the other way round.
I think we need to discuss this together before making any changes.

**Comment by jerome-benoit** [comment]
Modelling of AC/DC charging stations: 
+ A main AC charge point for inputs that share available power to all connectors whatever is their current output type;
+ Push down electrical specs at the connector level (current type, power, efficiency, etc.): all connectors belongs to the main charge point but can can use an inverter. 

I do not think that's necessary to add the inverter layer in the model, with the electrical specs attached to the connector, correct computation can be done. And that permits to keep the current template syntax, some properties must just also be allowed at connector, charging point level.

**Comment by jerome-benoit** [comment]
> > Compute correctly DC electrical outputs from AC inputs:
> > 
> > * Use conversion efficiency;
> 
> This is the contrary, if we say that the charger delivers 150kW DC then the AC part will consume more, then it is the other way round.
> I think we need to discuss this together before making any changes.

The efficiency given is always the efficiency of the AC->DC conversion (the inverter efficiency). The specs always give the AC nominal inputs (nominal amperage per phase). From there, you can deduce everything with the inverter efficiency and cope properly with charging stations mixing AC and DC outputs using the same power units.

**Comment by LucasBrazi06** [comment]
> The efficiency given is always the efficiency of the AC-> DC conversion (the inverter efficiency). The specs always give the AC nominal inputs (nominal amperage per phase). From there, you can deduce everything with the inverter efficiency and the number of phases and cope properly with charging stations mixing AC and DC outputs using the same power units.

And this is the case, the figures we're having is the DC in the Dashboard which is confusing.
We can discuss this tomorrow at the office.

**Comment by jerome-benoit** [comment]
> > The efficiency given is always the efficiency of the AC-> DC conversion (the inverter efficiency). The specs always give the AC nominal inputs (nominal amperage per phase). From there, you can deduce everything with the inverter efficiency and the number of phases and cope properly with charging stations mixing AC and DC outputs using the same power units.
> 
> And this is the case, the figures we're having is the DC in the Dashboard which is confusing.
> We can discuss this tomorrow at the office.

What matters for smart charging is the AC inputs properly computed. What matters for user is outputs. 
And currently we are using what matters for user for smart charging and static limitation: 
+ connectors DC outputs cannot be used directly, only the connectors real AC consumption matters here;
+ we do not care about the way such charging station share power inputs between connectors, what matters is the AC global inputs consumption. 

So we can have: 

+ charge points with no current type defined;
+ connectors with different current type defined;
+ output and input specs (amperage, power, voltage, efficiency, unit, etc.) for AC/DC at different levels (can be precomputed manually in the template to avoid overloading the controller tiers);
+ display outputs as default, optionally inputs;  
+ use inputs internally if necessary;
+ use outputs internally if necessary;
+ real time output and input consumption for AC/DC charging session graph (optional).

That way if a charging station firmware expect DC output power limitation in charging profile and AC global input amperage limitation for static limitation, we can compute it in the right values interval given the specs and another tunable stating what is expected and give the to optimiser the charging station inputs global consumption.

That will make the template syntax a bit more complex but the object to model is complex. And also the manual configuration form. But that's not really something that will be done by people that do not have a clue on what they are doing. And the end user keeps the outputs information as default.

**Comment by LucasBrazi06** [comment]
It is already working like this today, you just don't know it.
It's just the reading of the data in the UI/Template which can be improved.
And for the fucking third time, we will discuss it today so stop commenting here, this is not efficient at all and you know it.
