### ISSUE TITLE
Login > Email input must be lower cased at registration, user creation, etc.

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#2120]
Mixed case email address have occurred in DB on the QA landscape that have triggered login failure: user lookup on email address fails because lower case address is expected.

**Comment by LucasBrazi06** [comment]
email has always been case sensitive.
It's up to the user to enter the correct case for now (not a bug).
But we can indeed enforce email to lowercase + migration task.

**Comment by jerome-benoit** [comment]
Email-addresses can be considered case insensitive. 
It's in fact unsafe to treat email-addresses in a case-sensitive manner for authentication.

**Comment by LucasBrazi06** [comment]
> Email-addresses can be considered case insensitive.
> It's in fact unsafe to treat email-addresses in a case-sensitive manner for authentication.

I don't see what is unsafe here!
Anyway, I already wrote that we'll make it non sensitive.

**Comment by jerome-benoit** [comment]
It's because the unique identifier used for authentication of a unique user might not be unique in case of case sensitivity.
