### ISSUE TITLE
can't connect to the central server

### ISSUE THREAD

**Issue by JRGONGk** [sap-labs-france/ev-dashboard#2148]
My server is loading and running correctly.
My dashboard is also compiling properly.
When I access to localhost(with my IP address):45000 it loads the login panel , 
but when I enter the default superadmin  or any other given credentials, It gives error message "CAN'T REACH TO THE SERVER".

![2020-12-11 (2)](https://user-images.githubusercontent.com/51272647/101881858-0c868e00-3bbb-11eb-8b47-175ddca573f2.png)

**Comment by jerome-benoit** [comment]
You probably have mis-configured your dashboard. 
Could you please copy its src/assets/config.json file?

**Comment by JRGONGk** [comment]
This is my config.json file, in which I have added url = https://github.com/LucasBrazi06/ev-server.git in centralsystemserver. But it was'nt working before also.

{
  "CentralSystemServer": {
    "url": "https://github.com/LucasBrazi06/ev-server.git",	  
    "protocol": "http",
    "host": "107.191.44.218",
    "port": 80,
    "socketIOEnabled": true
  },
  "FrontEnd": {
    "host": "localhost"
  },
  "Authorization": {
    "debug": false
  },
  "Asset": {
    "maxImageKb": 800
  },
  "User": {
    "maxPictureKb": 150,
    "captchaSiteKey": ""
  },
  "Tenant": {
    "maxLogoKb": 150
	},
  "Company": {
    "maxPictureKb": 150
  },
  "Site": {
    "maxPictureKb": 800
  },
  "SiteArea": {
    "maxPictureKb": 800
  },
  "Car": {
    "url": ""
  },
  "Locales": {
    "default": "en",
    "supported": [
      "en",
      "fr",
      "es",
      "de",
      "pt"
    ],
    "fullSupported": [
      "en_US",
      "fr_FR",
      "es_MX",
      "de_DE",
      "pt_PT"
    ]
  },
  "Advanced": {
    "debounceTimeNotifMillis": 50,
    "debounceTimeSearchMillis": 500
  },
  "Debug": {
    "enabled": true
  }
}

**Comment by JRGONGk** [comment]
Hi! the above problem is solved.
I just removed the line "socketIOEnabled": true

**Comment by jerome-benoit** [comment]
> This is my config.json file, in which I have added url = [LucasBrazi06/ev-server.git](https://github.com/LucasBrazi06/ev-server.git) in centralsystemserver. But it was'nt working before also.
> 
> {
> "CentralSystemServer": {
> "url": "[LucasBrazi06/ev-server.git](https://github.com/LucasBrazi06/ev-server.git)",

That tunable have nothing to do with a git repository. It's the dashboard URI.

**Comment by jerome-benoit** [comment]
> Hi! the above problem is solved.
> I just removed the line "socketIOEnabled": true

That's not the root cause of that issue. The root cause is incorrect dashboard configuration. socket.io related tunable requires to be enable for have notifications working.

**Comment by fb2010** [comment]
> hat's not the root cause of that issue. The root cause is incorrect dashboard configuration. socket.io related tunable requires to be enable for have notifications working.

Could you please advise what is wrong with the provided config?
