### ISSUE TITLE
Sessions > Export: Format time using Charging Station's locale

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2170]

**Comment by cabch** [comment]
Need to have a closer look to the user local time as we don't have the timezone stored in the user, I can't find the place where the user time is formatted. 

Need to clarify which time needs to be displayed for the user compared to the charging station time (sorry I need a real life example here)

BEFORE we had
![BEFORE_MODIFICATIONS.png](https://images.zenhubusercontent.com/5fde23dcb9bf7af99a9b1ef4/928c5b52-a04b-4e78-9319-565f554c9f89)

TODAY I can have 
![AFTER_MODIFICATIONS.png](https://images.zenhubusercontent.com/5fde23dcb9bf7af99a9b1ef4/a3a3153e-2501-4581-a0fe-ddf8d16ecaaf)

**Comment by LucasBrazi06** [comment]
> Need to clarify which time needs to be displayed for the user compared to the charging station time (sorry I need a real life example here)

The first 3 columns is related to the transaction and you used the timezone to format it so that's okay.
And if it's confusing to have the 3 other columns, we can get rid of them.

**Comment by cabch** [comment]
I think that way is the clearer option, we only have the charging station time 

![Screenshot 2021-01-09 at 00.30.45.png](https://images.zenhubusercontent.com/5fde23dcb9bf7af99a9b1ef4/2ae986cc-f85b-4bc9-bbd7-6255ef1b7627)

**Comment by LucasBrazi06** [comment]
@cabch ok, that's perfect!

**Comment by LucasBrazi06** [comment]
To be tested in QA first before closing the task :-)
I reopen the task.
