### ISSUE TITLE
Assets > add missing properties

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-dashboard#2175]
- [x] Add static fallback value
- [x] Add fluctuation of asset
- [x] Add third asset type produce/consume
- [x] Turn values negative for produced energy

**Comment by OliveGerste** [comment]
> @OliveGerste One remark is that variable name 'fallbackValue' is only valid if you have a dynamic asset but not when you have a static one (no connection to a backend to get the value).
> I would call it more like 'staticValueWatt' (with the Unit also ;-))
> Also 'fluctuation' -> 'fluctuationPercent'?
> Let me know.

@LucasBrazi06 Hi Serge 
You are right, the variable name will not match for static assets. I will rename it.

I also thought about giving a percent value for the fluctuation. But it came in my mind, that the fluctuation depends on different devices which can be turned on or off. (so basically the fluctuation will be the same, if you consume 50kW with the assets or if you consume 1kW with the assests). 
When we have e.g. 30% for the fluctuation and 5kW consumption, we would only have 1.5kW (which is not much).

**Comment by LucasBrazi06** [comment]
> When we have e.g. 30% for the fluctuation and 5kW consumption, we would only have 1.5kW (which is not much for e.g. the whole building).

I thought more about the fluctuation being a % of the static consumption, if you have fluctuation = 30% and the static consumption is 50kW then it can vary by 15kW whatever the dynamic value.
What do you think?
