### ISSUE TITLE
Assets > Integration of Greencom 

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-dashboard#2176]

**Comment by LucasBrazi06** [comment]
@OliveGerste 
Solar Panel returns negative value:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/c4eab660-a50d-40da-88fa-056bf6cc09ff)
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/26ede7d8-2f99-432b-99c9-81b160e3b6b7)

And only local Site Area should be displayed:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/68964127-1db0-4b87-88a9-5796d5c54ac8)

**Comment by LucasBrazi06** [comment]
@OliveGerste 
Ensure also percentage of fluctuation is comprised between 0 and 100% in the UI and backend.
