### ISSUE TITLE
CSV - Translate headers

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2183]
Use the i18n files / tool to translate the headers in CSV with the user's locale.

For instance in class RemotePushNotificationTask:
    // Set the locale
    const i18nManager = new I18nManager(user.locale);
    // Get Message Text
    const title = i18nManager.translate('notifications.preparingSessionNotStarted.title');

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/1f40d42a-c548-4e07-b88d-74f93cfe1fab)

**Comment by WillyLellouch** [comment]
Does this include export csv ?
This is supposed to give the headers in the language of the current user locale right ?

**Comment by LucasBrazi06** [comment]
> Does this include export csv ?
> This is supposed to give the headers in the language of the current user locale right ?

Yes, all CSV exports
Yes with user's locale

**Comment by WillyLellouch** [comment]
The translation seems to work only with french (and english), all other languages use english headers.
I don't know whether it's because there are no translations yet for the others headers.

**Comment by LucasBrazi06** [comment]
> The translation seems to work only with french (and english), all other languages use english headers.
> I don't know whether it's because there are no translations yet for the others headers.

Yes this is the case, no translation yet for the other languages.
