### ISSUE TITLE
User > Account activation: Provide a setting to force an Admin to activate new user's account manually

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2192]
Scenario:
- User registers to the app
- User verify his account by clicking on the email link he received
- According the setting 'Manual account activation of new user':
  - If true: the user will receive a notification that his account has been verified and an Admin will activate it (status: 'Inactive') + admin will receive an email to handle the new registered user
  - If false: the user will receive a notification that his account has been verified AND activated (status: 'Active')
Setting to store in Technical Setting menu / new Tab 'User'
Consider also remote push notification
Clear message has to be displayed in the front-end
Differentiate Verify Account with Activate account if necessary in the backend/front-end/mobile app

This task can be done in two steps:
- [x] Implement the setting part + use it in account verification
- [x] Create migration task
- [x] Implement the notifications

**Comment by LucasBrazi06** [comment]
@cabch To be done next week if possible (requested by customer)
If you have not started the update token issue, you can switch to this one.
Thanks!

**Comment by LucasBrazi06** [comment]
@cabch Worked like a charm!!!
Well done!!!

**Comment by WillyLellouch** [comment]
Tested, the feature works as described. I noticed that the test server has it on, is this due to the client request ?

**Comment by LucasBrazi06** [comment]
> Tested, the feature works as described. I noticed that the test server has it on, is this due to the client request ?

Default is ON :)

**Comment by WillyLellouch** [comment]
Then Everything is OK
Tested without the feature also and it still works as before.
Closing Issue
