### ISSUE TITLE
OCPI: Investigate OCPIUtils.buildEvseID() -> Connector should always be provided

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2204]
Take the first connector is not acceptable: connectors can be null at a certain point of time and not after

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/25ea40dd-e47c-4949-af96-62835f96da51)

Side effect:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/3b3a2953-d133-472a-bab0-8d11cff3934f)

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/1671c07f-b856-4747-bebe-054a44694bff)

Should expect:
```
"uid": PROVIRIDIS-Puget-01,
"connectors": [
  {
    "id": "FR*PVD*EPROVIRIDIS*PUGET*01*1",
    ...
  }
],
```
Also why the 'E' in front of the charger:
FR*PVD*EPROVIRIDIS*PUGET instead of: FR*PVD*PROVIRIDIS*PUGET ?

Investigate the issues and if this is not expected evaluate if we can change without regressions.

**Comment by jerome-benoit** [comment]
I think that if the connector is not specified, then it must not be added to the string outputed. I will check if the expected string format have no requirement regarding the connectors information for the charging station level ("eMI3 standard version V1.0" (http://emi3group.com/documents-links) "Part 2: business objects."): https://github.com/ocpi/ocpi/blob/master/releases/2.1.1-d2/mod_locations.md
The loop that always add the first connector found is used in various other paths I doubt it must be used in all paths. 
In any case, a change to the uid field is a breaking and forbidden change:

uid | string(39) | 1 | Uniquely identifies the EVSE within the CPOs platform (and suboperator platforms). For example a database unique ID or the "EVSE ID". This field can never be changed, modified or renamed. This is the 'technical' identification of the EVSE, not to be used as 'human readable' identification, use the field: evse_id for that.
-- | -- | -- | --

Gireve must be contacted before we do it.

**Comment by jerome-benoit** [comment]
> Also why the 'E' in front of the charger:
> FR_PVD_EPROVIRIDIS_PUGET instead of: FR_PVD_PROVIRIDIS_PUGET ?

It part of the required format eMI3 format: 

```
The EVSE ID MUST match the following structure (the notation corresponds to the augmented BackusNaur Form (ABNF) as defined in RFC5234):
<EVSE ID> = <Country Code> <S> <Spot Operator ID> <S> <ID Type> <Power Outlet ID>

<ID Type> = “E”
; one character “E” indicating that this ID represents an “EVSE”
```

**Comment by LucasBrazi06** [comment]
> The EVSE ID MUST match the following structure (the notation corresponds to the augmented BackusNaur Form (ABNF) as defined in RFC5234):
> <EVSE ID> = <Country Code> <S> <Spot Operator ID> <S> <ID Type> <Power Outlet ID>
> 
> <ID Type> = “E”
> ; one character “E” indicating that this ID represents an “EVSE”

Okay, thanks Jerome, then maybe not needed in Hubject (copy/paste) :-)

**Comment by LucasBrazi06** [comment]
> Gireve must be contacted before we do it.

Ok, as discussed, check if we can replace the loop by an hardcoded number if connector is not provided.
In Hubject impl, I will ask Jakob to remove the copied/pasted code from OCPI :-)

**Comment by Jakob8** [comment]
Hubject uses the same standard (ISO 15118-1) for the EVSE ID.

> In case the EvseID is provided corresponding to ISO, the country code MUST be provided as Alpha-2-Code (DIN EN ISO-3166-1) and the separator character “*” is optional. Furthermore the ID MUST provide an “E” after the OperatorID in order to identify the ID as ISO EvseID without doubt. Examples ISO: “DE*AB7*E840*6487”, “DEAB7E8406487”

I can refactor the function into shared RoamingUtils to get rid of the copy.

**Comment by jerome-benoit** [comment]
> 
> Hubject uses the same standard (ISO 15118-1) for the EVSE ID.
> 
> In case the EvseID is provided corresponding to ISO, the country code MUST be provided as Alpha-2-Code (DIN EN ISO-3166-1) and the separator character “” is optional. Furthermore the ID MUST provide an “E” after the OperatorID in order to identify the ID as ISO EvseID without doubt. Examples ISO: “DEAB7E8406487”, “DEAB7E8406487”
> 
> I can refactor the function into shared RoamingUtils to get rid of the copy.
> 
> 
> 

Factor out the version with the fixes and report the fix made on OCPI to OICP.

Thanks.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by Jakob8** [comment]
Okay, I'll do after I can merge the master-qa into my branch

**Comment by jerome-benoit** [comment]
> Okay, I'll do after I can merge the master-qa into my branch
> 

I’ve merged master-qa in hubject-implementation and pushed it.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by LucasBrazi06** [comment]
@jerome-benoit No PR attached to this issue.

**Comment by LucasBrazi06** [comment]
My bad, wrong filtering in ZenHub!
