### ISSUE TITLE
Authorization: Match the e-Mobility JWT with the SAP JWT

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2206]
SAP user will be authenticated using SSO and the backend will receive the SAP JWT token:
- [ ] Provide on the fly e-Mobility JWT token creation based on the SAP one in an expressJS plugin
- [ ] If the SAP user does not exist, it should be created in e-Mobility as a Basic user
- [ ] Check that the backend works as expected
- [ ] Provide an unit test

The front-end will store the SAP JWT token in the local storage
- [ ] Identify and store the SAP JWT in the local storage
- [ ] Request the e-Mobility JWT token from the backend and use it in the app

**Comment by LucasBrazi06** [comment]
> @Fonsu you will have to work closely with @captaineaglex on that topic.
> 
> The latest commits on the approuter enables JWT token forwarding to the dashboard.

Both topics (auth refactoring) and SAP JWT front-end / backend integration can be treated separately.
So we can put Kartal on the integration of the SAP JWT token in // if he is ready.
Let me know.

**Comment by jerome-benoit** [comment]
> > @Fonsu you will have to work closely with @captaineaglex on that topic.
> > The latest commits on the approuter enables JWT token forwarding to the dashboard.
> 
> Both topics (auth refactoring) and SAP JWT front-end / backend integration can be treated separately.
> So we can put Kartal on the integration of the SAP JWT token in // if he is ready.

Sure but that issue is only about JWT token remapping. @captaineaglex is now focusing on the MTA integration to ease deployment. And I guess @Fonsu priority is on auth refactoring. 

When @Fonsu or @captaineaglex are ready to work on that issue, they just have to say so here. So there will happen no work duplication effort on the same topic.
