### ISSUE TITLE
Charging Station > Token: implement the Update of a token

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2225]

**Comment by LucasBrazi06** [comment]
@cabch 
Could you check the handling of the role Site Admin here + in the Unit Test?
Also it should be not possible to revoke a token that has expired (just add it in the unit test, it is changed in the front and backend)

**Comment by WillyLellouch** [comment]
Could I have a description of the use case here as well as the roles authorized to use this function ? Thanks

**Comment by LucasBrazi06** [comment]
> Could I have a description of the use case here as well as the roles authorized to use this function ? Thanks
@WillyLellouch request it to the dev by using the '@' ;-)
@cabch ?
