### ISSUE TITLE
Assets > Smart Charging: Trigger the smart charging when a threshold is exceeded

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-dashboard#2243]
Triggering of the Smart Charging:
- Latest consumption of the Asset when the smart charging is run is stored in a new Asset property
- When asset consumption is retrieved by the job, this value is compared with the current retrieved consumption
- Smart Charging is triggered when there is a change by 50% of the fluctuation (add a property in the Smart Charging settings)

**Comment by LucasBrazi06** [comment]
You can reuse the job that gather the consumptions

**Comment by OliveGerste** [comment]
Do we need an extra property here to define the threshold of the fluctuation? If yes where should we define it: in the asset, asset connection settings or smart charging settings?

**Comment by LucasBrazi06** [comment]
> Do we need an extra property here to define the threshold of the fluctuation? If yes where should we define it: in the asset, asset connection settings or smart charging settings?

The threshold I think is related to the asset, so I would make it specific to the asset

**Comment by OliveGerste** [comment]
Makes sense yes.
The naming is going to be challenging here. 
I would call the property something like 'fluctuationUtilizationThreshold'. What do you think?

**Comment by LucasBrazi06** [comment]
> The naming is going to be challenging here.
> I would call the property something like 'fluctuationUtilizationThreshold'. What do you think?

I think this has nothing to do with the fluctuation in the end but more on the variation of the consumption/production between two measures.
triggerActionOnVariationBetween2MeasuresPercent :D
triggerActionOnVariationPercent
variationThresholdPercent
...
:-)

**Comment by OliveGerste** [comment]
Maybe I am too complicated here. My plan was using the fluctuation as the base. So how much of the fluctuation is used by the asset: 
So e.g. Building Consumption: static value 100kW with Fluctuation 20% --> Fluctuation 20kW
variationThresholdPercent = 50% --> 50% of 20kW = 10 kW
So if it is exceeding 10kW we would call the smart charging. 

What you are suggesting is:
Building 100 kW, variationThresholdPercent = 10% --> 10 kW
If the consumption difference between the last smart charging call exceeds 10 kW we call the smart charging.
A bit easier and makes more sense, I have to admit :D So I will go for this approach.

**Comment by OliveGerste** [comment]
One last question on this one. 
Do we also call the smart charging if the production increase exceeds a certain threshold?
If yes I have the feeling that we will end up in a lot of smart charging calls with several assets and curves like this:
![image](https://user-images.githubusercontent.com/33114317/121211130-8783e500-c87c-11eb-9132-2cfb301c6c7e.png)

**Comment by LucasBrazi06** [comment]
> One last question on this one.
> Do we also call the smart charging if the production increase exceeds a certain threshold?
> If yes I have the feeling that we will end up in a lot of smart charging calls with several assets and curves like this:

Yes indeed but this is not a normal situation and in that case we will deactivate the threshold until the issue is solved.
Ok?

**Comment by OliveGerste** [comment]
Okay. I see this behavior quiet often for the solar panels actually, but maybe this is something to discuss with the asset provider. 

So the implementation will trigger smart charging if we have a consumption increase which exceeds the threshold and if have a decrease which exceeds the threshold.
