### ISSUE TITLE
Mobile: Error in Connector Details screen when charging a car and Session In Progress menu item is clicked in the side bar

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2250]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/ad73cc00-31dd-40a1-a916-1624fd4738e3)

**Comment by LucasBrazi06** [comment]
@AlixH Could you please check

**Comment by AlixH** [comment]
Test case : 

- [ ] Open the "sessions in progess" screen **from the Home Screen** for a user with exactly one session in progress. Then, open the drawer menu and select "Sessions in progress" => The sessions list is displayed.

**Comment by AlixH** [comment]
Test case : 

- [ ] Open the "sessions in progess" screen **from the Home Screen** for a user with exactly one session in progress. Then, open the drawer menu and select "Sessions in progress" => The sessions list is displayed.

**Comment by LucasBrazi06** [comment]
@AlixH Why did you close the issue?
