### ISSUE TITLE
Charging Station > Profiles: Profile is refreshed when being built

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2261]
Base the refresh of the profiles only on profile changes not on charging station.
Gerald reported the issue:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/1dadf665-6ebd-49fb-8dcc-2ea49a12a65e)

**Comment by OliveGerste** [comment]
Could you explain this issue a bit more? Currently the charging profile is refreshed, when any change is made to the charging profiles collection. What is expected here?

**Comment by LucasBrazi06** [comment]
> Could you explain this issue a bit more? Currently the charging profile is refreshed, when any change is made to the charging profiles collection. What is expected here?

You can contact Gerald, he will show you.
Let me know.

**Comment by cybergege** [comment]
While trying to manually create a charge plan, the auto refresh erase all the lines before I have the time to save.
Solved by deactivating the refresh button
Let me know If you can't reproduce

**Comment by OliveGerste** [comment]
I had a look at the code, but I am not sure why the Charging Profiles are refreshing when the charging stations are refreshed. I have not been able to find the error.

@jerome-benoit  
Do you have an idea, why this happens?

**Comment by LucasBrazi06** [comment]
> I had a look at the code, but I am not sure why the Charging Profiles are refreshing when the charging stations are refreshed. I have not been able to find the error.
> 
> @jerome-benoit
> Do you have an idea, why this happens?

When the status of a connector is refreshed, you receive a notification and the charging station instance is reloaded triggering the whole chain that will reload the charging profile while you are changing them.

**Comment by jerome-benoit** [comment]
> > I had a look at the code, but I am not sure why the Charging Profiles are refreshing when the charging stations are refreshed. I have not been able to find the error.
> > @jerome-benoit
> > Do you have an idea, why this happens?
> 
> When the status of a connector is refreshed, you receive a notification and the charging station instance is reloaded triggering the whole chain that will reload the charging profile while you are changing them.

Previously, the `@Injectable` decorator was wrongly added to the component inhibiting OnInit, OnChange, etc. implementation to work as expected and the angular native refresh was not working at all (ngOnChanges never called). 
Now that's `@Injectable` is properly used in the dashboard code, refresh occurs has expected or for that component on events that should be ignored. I think that if you filter the event triggering the refresh, you will be able refresh only if needed.

**Comment by LucasBrazi06** [comment]
> Now that's `@Injectable` is properly used in the dashboard code, refresh occurs has expected or for that component on events that should be ignored. I think that if you filter the event triggering the refresh, you will be able refresh only if needed.

Yes, that could be a solution: do not refresh the charging profiles while you are changing them.
