### ISSUE TITLE
Asset > Create: Issuer flag should be set to true

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2266]
- [x] When created, issuer flag is not set, should be true
- [x] Check in unit test
- [x] When Asset is assigned to a Site Area, filter with issuer flag = true

**Comment by OliveGerste** [comment]
@LucasBrazi06  
Does the task include a migration task? and further checks for updating and deleting assets regarding the issuer flag?

**Comment by OliveGerste** [comment]
@LucasBrazi06 
Any news on this one?

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06
> Any news on this one?

Sorry, didn't notice your first comment!
Yes, we need a migration task to set to true the issuer of all the existing assets.
