### ISSUE TITLE
Integration settings display wrongly settings with non existing settings error notification message

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#2271]
Reproducible on Proviridis tenant.

**Comment by LucasBrazi06** [comment]
More details on the issue:
When Analytics or Smart Charging is clicked, Angular tries to load the settings from the backend but it should not and get an error in trying to do so:
![image](https://user-images.githubusercontent.com/25266945/109123625-5a3a7d80-774a-11eb-9885-f332b4158463.png)
Check with a tenant with no components activated that no requests is sent to load settings.
