### ISSUE TITLE
RESTful / Schema : Migrate Transactions service endpoint

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2274]
Start migrating 1 endpoint and make a PR. Next proceed with 3 by 3 + PR
- [x] Add Transaction's REST service path in RESTful API
- [x] Add the new RESTful endpoints in the OAS file
- [x] Update the Unit Tests
- [x] Update the Front-end Http calls (make PR)
- [x] Update the Mobile App Http calls (after backend/front-end deployment in prod)
- [x] Validate HTTP queries with JSon schemas in Transaction service class (start with 1 endpoint and make a PR and next 3 by 3 + PR)
- [x] Update the Postman collection
- [x] Remove Transaction's security class
- [ ] Remove Transaction's old endpoint

@Ninjeneer
Starts with getTransactions in priority (customer's need)

**Comment by LucasBrazi06** [comment]
@Ninjeneer I just started the getTransactions endpoint as it has to be delivered asap

**Comment by LucasBrazi06** [comment]
@Ninjeneer getTransactions has be done.

**Comment by Ninjeneer** [comment]
In advance, here is a proposal for the transactions REST routes :

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/I511607/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/I511607/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



Action | Old HTTP Method | Old route | New HTTP Method | New Route
-- | -- | -- | -- | --
TRANSACTIONS | GET | /Transactions | GET | /transactions
TRANSACTIONS_DELETE | DELETE | /TransactionsDelete | DELETE | /transactions
TRANSACTION | GET | /Transaction | GET | /transactions/:id
TRANSACTION_DELETE | DELETE | /TransactionDelete | DELETE | /transactions/:id
TRANSACTION_PUSH_CDR | POST | /TransactionPushCdr | POST | /transactions/:id/ocpi/cdr
TRANSACTION_OCPI_CDR_EXPORT | GET | /TransactionsOcpiCdrExport | GET | /transactions/:id/ocpi/cdr/action/export
TRANSACTION_CONSUMPTION | GET | /TransactionConsumption | GET | /transactions/:id/consumption
REBUILD_TRANSACTION_CONSUMPTIONS | GET | /RebuildTransactionConsumption | POST | /transactions/:id/consumption/rebuild
TRANSACTION_SOFT_STOP | PUT | /TransactionSoftStop | PUT | /transactions/:id/stop/soft
TRANSACTIONS_REFUND | POST | /TransactionsRefund | POST | /transactions/action/refund
ASSIGN_TRANSACTIONS_TO_USER | PUT | /AssignTransactionsToUser | PUT | /transactions/action/assign
TRANSACTIONS_EXPORT | GET | /TransactionsExport | GET | /transactions/action/export
SYNCHRONIZE_REFUNDED_TRANSACTIONS | POST | /SynchronizeRefundedTransactions | POST | /transactions/status/refunded/synchronize
TRANSACTIONS_COMPLETED | GET | /TransactionsCompleted | GET | /transactions/status/completed
TRANSACTIONS_TO_REFUND | GET | /TransactionsToRefund | GET | /transactions/status/to-refund
TRANSACTIONS_TO_REFUND_EXPORT | GET | /TransactionsToRefundExport | GET | /transactions/status/to-refund/action/export
TRANSACTIONS_TO_REFUND_REPORTS | GET | /TransactionsToRefundReports | GET | /transactions/status/to-refund/reports
TRANSACTIONS_ACTIVE | GET | /TransactionsActive | GET | /transactions/status/active
TRANSACTIONS_IN_ERROR | GET | /TransactionsInError | GET | /transactions/status/in-error
UNASSIGNED_TRANSACTIONS_COUNT | GET | /UnassignedTransactionsCount | GET | /transactions/status/unassigned/count



</body>

</html>

There is also a TRANSACTION_YEARS action, but I think it belongs better to statistics endpoints than transactions ones, what do you think ?

**Comment by LucasBrazi06** [comment]
Ok for the stats.

In plural?
- /transactions/:id/consumption -> /transactions/:id/consumptions ?
- /transactions/status/refunded/synchronize -> /transactions/action/refund/synchronize ?

Should be deleted (use QueryString)?
- /transactions/status/completed -> /transactions?Status=completed
- /transactions/status/to-refund -> /transactions?Status=refund
- /transactions/status/active -> /transactions?Status=active
- /transactions/status/unassigned/count -> /transactions?Status=not-assigned-to-user
- /transactions/status/to-refund/action/export -> /transactions/action/export?Status=refund

**Comment by Ninjeneer** [comment]
> In plural?

Sure!

> Should be deleted (use QueryString)?

Make sense, but it would be inconsistent against the already existing "charging-stations/status/in-error". Should I refactor this one to use QueryStrings ? (Or even better, keep this one alive to maintain retro-compatibility and add a new one with QueryStrings) ?

**Comment by LucasBrazi06** [comment]
> Make sense, but it would be inconsistent against the already existing "charging-stations/status/in-error". Should I refactor this one to use QueryStrings ? (Or even better, keep this one alive to maintain retro-compatibility and add a new one with QueryStrings) ?

Yes x2 :-)
