### ISSUE TITLE
Authorization > Site: Check if the Site is auth based

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2297]
- [ ] Display the Site tab only if authorized to list sites
- [x] In the REST endpoint (backend), double check the list sites auth + implement project/filters based on user assignment to sites
- [ ] Check edit action against edit site auth and display the Edit button otherwise show the Display button
- [ ] Check delete action against delete site auth and hide it if not authorized
- [x] Check the unit tests and eventually add the missing ones

**Comment by roxiciobotea210** [comment]
I have a question regarding the final contents of the token - will we keep `sitesAdmin` and `sitesOwner` in the token? Or will they also be removed? 
I'm asking so I know if I can use this information in the checks directly from the user token.

**Comment by LucasBrazi06** [comment]
@roxiciobotea210 @Fonsu Just to mention that your PR is still in Requested Changes pipeline ;-)

**Comment by roxiciobotea210** [comment]
> @roxiciobotea210 @Fonsu Just to mention that your PR is still in Requested Changes pipeline ;-)

I forgot to move it. :( It is in To Be Reviewed now.

**Comment by LucasBrazi06** [comment]
> I forgot to move it. :( It is in To Be Reviewed now.

Yes, I guessed that this is taking too much time ;-)
