### ISSUE TITLE
Unlock Connector : ConnectorId should be an Integer instead of a String

### ISSUE THREAD

**Issue by WillyLellouch** [sap-labs-france/ev-dashboard#2312]
For the Unlock Connector Action in Charging Stations, the application communicates an incorrect ConnectorId to the CS.
The current format is a String but it should be an Integer.

**Comment by LucasBrazi06** [comment]
@Ninjeneer Could you please check if this one is fixed with your latest PR?

**Comment by Ninjeneer** [comment]
@LucasBrazi06 Yes it is, schemas automatically cast inputs according to required type

**Comment by LucasBrazi06** [comment]
@WillyLellouch According Loan, it will be fixed in the next deployment V2.4.53 (normally tonight)
