### ISSUE TITLE
Authorization > Check canCreate flag to toggle create button visibility (companies/sites)

### ISSUE THREAD

**Issue by Fonsu** [sap-labs-france/ev-dashboard#2332]
Example: the admin user can create a payment method for the Billing but only for himself in his user's profile but cannot create one for the other users. In that case we have to hide the Create button. This enhancement will further improve the authorization's granularity.

This issue covers companies and sites.

![image.png](https://images.zenhubusercontent.com/5fbbe737956d0a9258d321f8/918131e0-b312-48b6-a0f1-ba24b730320c)

**Comment by LucasBrazi06** [comment]
@Fonsu You can also align the DataResult types with the backend

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/909364d7-2d35-47cd-92d8-45eaa9f397ae)
