### ISSUE TITLE
Badges: Allow deleting badges with transactions + Check linked transactions when create/ reassign a badge

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2366]
@mahdibenromdhane evaluate the effort and the impact first and we can check if we go for it or if we try to find another way to handle the archived tag.

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane evaluate the effort and the impact first and we can check if we go for it or if we try to find another way to handle the archived tag.

@LucasBrazi06 There is less impact and changes if we go with "setting inactive and userID kept -> Cannot assign the badge anymore" as suggested in the pervious PR.
Replacing active flag by status will provoke many changes in the server and in the dashboard.

**Comment by mahdibenromdhane** [comment]
> > @mahdibenromdhane evaluate the effort and the impact first and we can check if we go for it or if we try to find another way to handle the archived tag.
> 
> @LucasBrazi06 There is less impact and changes if we go with "setting inactive and userID kept -> Cannot assign the badge anymore" as suggested in the pervious PR.
> Replacing active flag by status will provoke many changes in the server and in the dashboard.

We can go for setting inactive and keep the userID for now and keep this issue for later because I think it's more organised if we follow the way suggested in this issue.

**Comment by LucasBrazi06** [comment]
> We can go for setting inactive and keep the userID for now and keep this issue for later because I think it's more organised if we follow the way suggested in this issue.

What if we really delete the Tag and we enforce the check at creation time?
If there is a transaction with this tag, we simply reject the creation with a concise message.
What do you think?

**Comment by mahdibenromdhane** [comment]
> > We can go for setting inactive and keep the userID for now and keep this issue for later because I think it's more organised if we follow the way suggested in this issue.
> 
> What if we really delete the Tag and we enforce the check at creation time?
> If there is a transaction with this tag, we simply reject the creation with a concise message.
> What do you think?

For now if we delete the user we delete also his tags and we reject the creation of the same tag if there is counted Transactions with this tag ID (last PR).
We can apply the same scenario with the use case 'Delete Tag' and we can add concise message.

**Comment by LucasBrazi06** [comment]
> For now if we delete the user we delete also his tags and we reject the creation of the same tag if there is counted Transactions with this tag ID (last PR).

So It works as expected for now :-)

> We can apply the same scenario with the use case 'Delete Tag' and we can add concise message.

Yes we can have a concise message that the same tag couldn't be created anymore.

**Comment by mahdibenromdhane** [comment]
> > For now if we delete the user we delete also his tags and we reject the creation of the same tag if there is counted Transactions with this tag ID (last PR).
> 
> So It works as expected for now :-)
> 
> > We can apply the same scenario with the use case 'Delete Tag' and we can add concise message.
> 
> Yes we can have a concise message that the same tag couldn't be created anymore.

Ok :)
