### ISSUE TITLE
Display meaningful error message when manual configuration checkbox fails to be changed 

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-dashboard#2411]

**Comment by jerome-benoit** [comment]
The issue is also happen on charging station online: the SAP Keba for example on testcharger tenant on QA. So it's also a bug.

**Comment by OliveGerste** [comment]
Hello Jerome could you give me a bit more information, what needs to be done?
I had a look at the logs from the station and it seems, that it does not find a template for it: 
![image](https://user-images.githubusercontent.com/33114317/120772902-144b3d80-c521-11eb-96d4-8dbcbace1dfc.png)

**Comment by jerome-benoit** [comment]
Right. 

But no error popup message is display, even stating to check the logs, the configuration switch is reverted without explanation.

**Comment by OliveGerste** [comment]
Okay you are right. I think we have a bug in the front end, that we cannot uncheck the manual configuration box. 
I will have a look.

**Comment by jerome-benoit** [comment]
And I will fix the templates to add that model.
With the simulator, you can easily have a charging station without matching template to reproduce.

**Comment by OliveGerste** [comment]
@jerome-benoit The bug is happening because the charging station has never been saved before, so the manual config parameter is not yet in the database. 
So once the station was saved it should be possible to switch it to automatic.

**Comment by jerome-benoit** [comment]
It should work without requiring to save it ...

**Comment by OliveGerste** [comment]
Normally yes, but in my opinion we will never have this specific case at a customer.
To run into this issue the following must happen: 
The customer onboards a station without a template and then switch it immediately to automatic (even if still no template is available). Normally he should fill the parameters of the station manually and save it.

**Comment by jerome-benoit** [comment]
We have it on on several customer tenant that do their own charging stations: exadys for example.

**Comment by LucasBrazi06** [comment]
> Normally yes, but in my opinion we will never have this specific case at a customer.
> To run into this issue the following must happen:
> The customer onboards a station without a template and then switch it immediately to automatic (even if still no template is available). Normally he should fill the parameters of the station manually and save it.
> After this he can switch to automatic anytime.

Sorry for the intrusion :-) but the switch from manual to automatic should not never be displayed when no template is available for the charging station.

**Comment by jerome-benoit** [comment]
The REST API for charging stations does not give that information.

**Comment by LucasBrazi06** [comment]
> The REST API for charging stations does not give that information.

Make it happen.
