### ISSUE TITLE
Badge ID is set to '0' when acces control is disabled in Site Area

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2498]
Badge ID should not be set to "0" when ACL is not active in Site Area:

![2021-07-11_16-11-38.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/c8cb28dd-6a33-4261-a32e-158a99d6dd7c)

'null' should be stored in DB and returned in the UI and '-' should be displayed in the list.
Maybe a migration task should be necessary to cleanup the DB.

**Comment by mahdibenromdhane** [comment]
Not reproducible
