### ISSUE TITLE
Invalid captcha token issue

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-dashboard#2529]
Hello Community 

I have setup google recaptcha key properly 

in both sitekey and secretkey properly  in ev-dashboard and ev-server 

but on the registration giving the following error: **Invalid captcha token**

![image](https://user-images.githubusercontent.com/32220165/129514808-7547b20f-bdee-4c32-bf1c-091d727ff200.png)

Please do advise , i am using latest version of ev-server

**Comment by LucasBrazi06** [comment]
@rccess Hello, sorry, just got back from holiday.
Have you checked the backend's logs? (check with Robo3T directly in the DB).

**Comment by LucasBrazi06** [comment]
Closed for inactivity reason.
