### ISSUE TITLE
Badges refactoring

### ISSUE THREAD

**Issue by mahdibenromdhane** [sap-labs-france/ev-dashboard#2546]
- Basic should register his own Badge (using the visual tag ID)
- New authoizations definitions for basic user. 
- UI for Register/Unregister/Edit Badge for Basic User only
- Move Badge to a dedicated menu tab (out of users tab)
- Make user not mandatory in badges for admin (can remove user from badge or create badge without a user)

**Comment by LucasBrazi06** [comment]
User is displayed for site admin.
I think that the User field should not be displayed:
![2021-09-10_17-34-55](https://user-images.githubusercontent.com/25266945/132879801-34976e4a-8df2-43b1-9e5c-70a9569f2ed6.png)

**Comment by LucasBrazi06** [comment]
Site Admin has two Edit buttons:
![2021-09-10_17-38-03](https://user-images.githubusercontent.com/25266945/132880008-cb45e009-149a-4e35-828c-5581d1298a5a.png)

**Comment by LucasBrazi06** [comment]
When menu Tag is selected, we can see for a short period of time the hidden buttons in the toolbar.
These button should be hidden by default and displayed afterwards.

**Comment by LucasBrazi06** [comment]
![2021-09-10_18-11-42](https://user-images.githubusercontent.com/25266945/132884511-25213857-9a81-4eaa-a96d-fe999233fc8d.png)

**Comment by LucasBrazi06** [comment]
Basic User can change props of an Inactive tag (made inactive by an Admin): It should not be able to edit it I think.

**Comment by LucasBrazi06** [comment]
Basic User can unset its default badge and got no default assign to him:

![2021-09-10_18-21-59](https://user-images.githubusercontent.com/25266945/132885786-0158bd85-0b03-416c-baec-7f6c19bccd92.png)

**Comment by mahdibenromdhane** [comment]
> Basic User can unset its default badge and got no default assign to him:
> 
> ![2021-09-10_18-21-59](https://user-images.githubusercontent.com/25266945/132885786-0158bd85-0b03-416c-baec-7f6c19bccd92.png)

Done.

**Comment by mahdibenromdhane** [comment]
> Basic User can unset its default badge and got no default assign to him:
> 
> ![2021-09-10_18-21-59](https://user-images.githubusercontent.com/25266945/132885786-0158bd85-0b03-416c-baec-7f6c19bccd92.png)

Done.

**Comment by mahdibenromdhane** [comment]
> User is displayed for site admin.
> I think that the User field should not be displayed:
> ![2021-09-10_17-34-55](https://user-images.githubusercontent.com/25266945/132879801-34976e4a-8df2-43b1-9e5c-70a9569f2ed6.png)

Done.

**Comment by mahdibenromdhane** [comment]
> Basic User can change props of an Inactive tag (made inactive by an Admin): It should not be able to edit it I think.

Done.

**Comment by mahdibenromdhane** [comment]
> When menu Tag is selected, we can see for a short period of time the hidden buttons in the toolbar.
> These button should be hidden by default and displayed afterwards.

Done.
