### ISSUE TITLE
Empty OCPP URL

### ISSUE THREAD

**Issue by danielrama30** [sap-labs-france/ev-dashboard#2574]
![Screenshot from 2021-09-21 13-01-03](https://user-images.githubusercontent.com/43497685/134161160-107610a7-3ad8-4b36-ae3c-06a7ce0f8655.png)
the box where the OCPP URL should be is empty.
At the moment the server is on localhost only, could this be the cause?

**Comment by danielrama30** [comment]
both dashboard and server .json files seem fine to me, I only edited the params written in the configuration guide. What should I check for?

**Comment by danielrama30** [comment]
Sorry for late reply, I wasn't office yesterday. 
I guess that param should contain a websocket link, but how should be build this link? I know the  charger ID must be at the end of the link but I don't know the directory the link need to point

**Comment by LucasBrazi06** [comment]
> Sorry for late reply, I wasn't office yesterday.
> I guess that param should contain a websocket link, but how should be build this link? I know the charger ID must be at the end of the link but I don't know the directory the link need to point

Put the URL of your Json server, that's it the rest is done automatically.

**Comment by danielrama30** [comment]
ok got it
