### ISSUE TITLE
add charging station section missing on dashboard

### ISSUE THREAD

**Issue by Pulse-akhil** [sap-labs-france/ev-dashboard#2581]
First of all, thank you for this repo. It's very helpful in ramping up on the different nuances of an OCPP server. 

Second, I got the ev-server and ev-dashboard up and running. But I don;t see add a charging station section in the dashboard? is that intentional.

**Comment by LucasBrazi06** [comment]
You welcome :)
You have multi-tenancy (organizations) in the Dashboard.
Create a new organization (validate it with email...) and with the <subdomain>.localhost:45000, you'll see everything you looked for after loging in.

**Comment by Pulse-akhil** [comment]
Excellent, thank you so much. Loving every bit of playing around with this platform.
