### ISSUE TITLE
OCPP token not showing

### ISSUE THREAD

**Issue by terryjoshua** [sap-labs-france/ev-dashboard#2734]
Hi, 

I really appreciate your app very much. 
I installed and ran ev-server and ev-dashboard successfully.
When I tried to create "registration token", I could not get token URL string by clicking button (Copy OCPP URL) as shown below.

![image](https://user-images.githubusercontent.com/6228139/141185452-4a73db91-7abb-4e31-b30e-3f918caaff48.png)

I had hard time to add ev-simulator charging station. I could not see any useful log in mongodb defaults.logs.
Any Help would be greatly appreciated.

Thanks,

**Comment by LucasBrazi06** [comment]
If you don't have the URL tokens, it probably due to a missing configuration in config.json file (JsonEndpoint.baseSecureUrl).
It should point to your Json server when the chargers should be connected.

default.logs are only for the master tenant where you create the organizations.
Once you have the org created the logs are in the <org-id>.logs.

Voila :-)

**Comment by terryjoshua** [comment]
Thank you very much for your replay.

I believe you want to edit  "ev-server/src/assets/config.json"
But I could not find JsonEndpoint.baseSecureUrl. Instead, I found the following line and add "baseUrl" llike below.
 
  "JsonEndpoint": {
    "baseUrl": "ws://xxx.mydoman.com:8010/"
  },

But I still could not get token URL value. It shows nothing when I click the button.

I found from other thread that OCPP token URL looks like below.

"ws://xxx.mydomain.com:8010/OCPP16/618ab638b7e82e96b02c80ca/618ab47eb7e82e96b02c8038"

I can access MongoDB. Could you please show me how to create token URL value from MongoDB?

Thanks in advance.

**Comment by LucasBrazi06** [comment]
> But I could not find JsonEndpoint.baseSecureUrl. Instead, I found the following line and add "baseUrl" like below.

Indeed, this is a recent change to only support secure WSS connection.
I just updated the conf templates in master-qa, please use:

```
  "JsonEndpoint": {
    "baseSecureUrl": "wss://xxx.mydoman.com:8010/"
  },

```

You should have then your links in the UI.

**Comment by terryjoshua** [comment]
Thanks a lot for quick reply.
It worked!!!! I was able to get Secure OCPP URL from dashboard.
However, ev-simulator still could not connect to central server. 
I think I did not follow instructions properly. It gave me "syntax error".
I will do my homework and create new issue to proper "issue" board if necessary.

Thanks again for your help.

**Comment by LucasBrazi06** [comment]
You welcome!
My pleasure!

Ok let me know for the ev-simulator.
It's not very well implemented (lots of devs wrote code in here and I didn't spend time in reviewing it.)
