### ISSUE TITLE
Cannot edit charger parameters

### ISSUE THREAD

**Issue by danielrama30** [sap-labs-france/ev-dashboard#2864]
After we added a new charger we cannot edit it's parameters and we can't assign it to a site area.
Everything is configured correctly, and the error seems about a variable not present , also got a screenshot of the error and logs
![Cattura1](https://user-images.githubusercontent.com/43497685/146923088-c23683d3-a602-45e5-93c4-b8d709d912ff.PNG)
![Cattura](https://user-images.githubusercontent.com/43497685/146923114-0d3f8276-ee28-459a-973a-15367f521859.PNG)

**Comment by danielrama30** [comment]
Forgot to mention we actually run version 2.5.9 but looking the changelog of newer versions there is no mention of this bug

**Comment by LucasBrazi06** [comment]
Sorry for the late answer, holiday periods.
Always upgrade to the latest version, we do not provide hotfix to former releases.
In the meantime, I'll close this issue.
