### ISSUE TITLE
Docker run failed!

### ISSUE THREAD

**Issue by IstiyakV** [sap-labs-france/ev-dashboard#2906]
tried lots of time to clone this git and run it via docker. but all time get error

**Comment by LucasBrazi06** [comment]
What kind of error do you have?

**Comment by IstiyakV** [comment]
this issue is only with the master-qa branch the error is "could not find a recursive git" something like that. I tried with the master branch and there I faced a git error problem then I solved it with the git init command. now it's running.

**Comment by LucasBrazi06** [comment]
Give me the right error message lol and not 'something like that' ;-) as well as the line which made it failed.
Let me know.
