### ISSUE TITLE
Default values for filetring on dates is too strict

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-dashboard#2952]
The default values for filtetring on dates puts the current time as the upper limit.
This is not convenient at all, because if you wait on that screen and press refresh, you then do not get any new data anymore.
Same frustration when using the "Auto refresh" option. No new data will be shown.

Can we just make sure the upper limit is in the future (at least the end of the day)?
Thanks.

<img width="1195" alt="2022-01-26_13-45-29" src="https://user-images.githubusercontent.com/26900551/151165413-16707c47-1ed7-4803-9b1e-f0489d6afafe.png">

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI I already reported this problem to Rohan yesterday :-)

**Comment by LucasBrazi06** [comment]
Dups of #2950
