### ISSUE TITLE
Date range filter - 'Date to' is systematically reset when list is refreshed...

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-dashboard#2967]
If I set a date range in the past, the "date to" is systematically reset to the current date/time but it should not change once set by the user.
So at first init, the 'date to' should be set 24h in the future or at the end of the day and never touched again whenever we refresh the UI.
Let me know.

**Comment by RohanAntony** [comment]
Isn't it a better option to add a (toggle like auto refresh / checkbox) beside date range filter. 
When "ON", it will update the "date to" to lastest value for every refresh. 
When "OFF" the refresh wouldn't update the "date to". 
By default, we set it this option to "ON".

![image](https://user-images.githubusercontent.com/5779016/152808664-d644baa8-8506-4f8e-be5f-a40406d6ec4a.png)
