### ISSUE TITLE
Fix filter date when jumping sessions to logs

### ISSUE THREAD

**Issue by KinzaBS** [sap-labs-france/ev-dashboard#2991]
Filter on the logs is not correct. 

![image.png](https://images.zenhubusercontent.com/5fff514ae5960a4fafaf6289/75c82e81-6ff0-4a51-8599-8d648418d847)

**Comment by KinzaBS** [comment]
@LucasBrazi06  Hello Serge, is it a new bug? 
@ClaudeROSSI

**Comment by LucasBrazi06** [comment]
@RohanAntony Could you please have a look?

**Comment by RohanAntony** [comment]
@KinzaBS Did you navigate to logs from a sessions history, in error or in progress tab here?
