### ISSUE TITLE
Hosting main dashboard under a subdomain

### ISSUE THREAD

**Issue by ramukv** [sap-labs-france/ev-dashboard#3038]
Tried the setup (ev-server and dashboard) on `localhost` and it worked fine. But when the dashboard url has a subdomain (say while using ngrok or hosting on AWS) I am not able to login or register as the server returns a 500 error. 

It seems the dashboard sends the subdomain as the `tenant` param in the request and this is sort of causing the issue as the server looks for a tenant with the given subdomain.

How are we supposed to host the main dashboard under a subdomain like `sd.example.com`

Following is the chrome console error on API call
<img width="1034" alt="Screenshot 2022-03-17 at 12 16 04 AM" src="https://user-images.githubusercontent.com/101744680/158664524-e7186f81-801a-4397-b92e-9be006a4689a.png">

Also I don't see much debug logs on the server container even after setting the `D` log levels. Am I missing something?

**Comment by lblabr** [comment]
you need to configure the backend server in assets/config.json (ev_dashboard Container)

**Comment by ramukv** [comment]
@lblabr the `CentralSystemServer` is already configured to use `localhost:81` as you can see from the console logs. Or am I missing some configuration on the `ev-server` side?

What I meant is the `ev-dashboard` should treat `sd.example.com` as the master tenant (like it does for `localhost`) and not as a sub tenant. How does it figure out the default host domain for the master tenant?

If possible could you please post a sample config?

**Comment by LucasBrazi06** [comment]
> What I meant is the `ev-dashboard` should treat `sd.example.com` as the master tenant (like it does for `localhost`) and not as a sub tenant. How does it figure out the default host domain for the master tenant?

Everything in front of the domain name is treated as a subdomain to figure out the tenant name.
It's done in the window.service.ts
![image](https://user-images.githubusercontent.com/25266945/167384110-a00f03cb-8fdd-44cc-be39-24d1030adae0.png)
