### ISSUE TITLE
eula is not displayed

### ISSUE THREAD

**Issue by lblabr** [sap-labs-france/ev-dashboard#3039]
nothing is displayed by hitting the end user licence link. 
by using tcpdump on port 81 of the server, no request can be seen from dashboard. 
so far as i could see, the eula is stored in the database backend and it looks like, that eula is not requestet by an api call from dashboard.

i'm not an web developer, how do the link /auth/eula gets routed ?

could you pls give a hint where to start to debug?

thanks in advance

Lars

**Comment by LucasBrazi06** [comment]
I fixed a bug lately with the EURL.
Check with this link by replacing the host/port with the ones of your REST server (triggered by the Dashboard):
https://rest.e-mobility-group.com/v1/auth/eula?Language=en
