### ISSUE TITLE
Upgrade > WS Connection with URL '/IPElms' is invalid: No 'OCPP16' or 'REST' in path

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-dashboard#3091]
Hello Serge
I have a question about the connection between the server and the charging station. As a beginner I am not quite sure where to enter the data for a successful connection. 
The server and dashboard are successfully built. The Ws connection with the charging station does not work. 
I am sending you the screenshots of the error messages and the config.json in the attachment. 
Many thanks already
![Server](https://user-images.githubusercontent.com/86152408/164413756-e508216c-2553-4cb7-8057-b041929e791b.PNG)
![Dashboard](https://user-images.githubusercontent.com/86152408/164413789-ac065f5d-12a0-4f1b-9460-6fcf144f666a.PNG)
![Logs](https://user-images.githubusercontent.com/86152408/164413804-510184e6-c58a-472e-b0f0-c2dee7e9db97.PNG)
![ChargingPointSettings](https://user-images.githubusercontent.com/86152408/164414712-0f1cce54-7b5d-4024-bed5-1b0d9d159b99.PNG)

[config.json.txt](https://github.com/sap-labs-france/ev-dashboard/files/8529166/config.json.txt)

**Comment by LucasBrazi06** [comment]
Hello!
It means that the charging station (CS) is not connecting with the full ws URL!
It's more a problem on the CS side.
You can check the logs of the CS.

**Comment by Gregor193** [comment]
Many thanks for the quick feedback
I will have a look at the logs and if necessary contact the manufacturer of the charging station.
