### ISSUE TITLE
Wrong Numbers of arguments in URL

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-dashboard#3093]
Hello, 
I have tried running the EV simulator in conjunction with the EV server and the EV dashboard. 
However, I get the following error message for each charging station. Can you help me in which places I have to make changes to get the simulation to run.
Thanks a lot 
![SimulatorIssue](https://user-images.githubusercontent.com/86152408/165054326-376ee81c-85f8-422c-8e41-2e86e0af7b63.PNG)

**Comment by LucasBrazi06** [comment]
You must generate a token from the front-end (charging-stations menu)

**Comment by Gregor193** [comment]
Thank you
I have now generated the token and added it to the simulator's config.json. 

![Config JsonSimulator](https://user-images.githubusercontent.com/86152408/165061500-1fe2ec52-df90-4324-b815-0bfed1e4649f.PNG)

Unfortunately, I do not recognise any connection attempt with the simulator in the logs. What could be the cause of this? Possibly an incorrect JsonEndpoint in the config.json of the server, from which the URL is generated? 
I get the following message after building the server: 

![Endpoint targetPort](https://user-images.githubusercontent.com/86152408/165061538-b9938f95-597d-46ce-9a01-fc23b143edde.PNG)

As a programming beginner, I have not yet fully understood the purpose of the json endpoint. Currently, it looks like this for me:  

![JsonEndpoint](https://user-images.githubusercontent.com/86152408/165061565-083f53b2-69e9-4a3c-a536-2053c36e43d8.PNG)


Can you help me with this?

**Comment by LucasBrazi06** [comment]
Your server is listening on locahost:8010 and you try to connect the simulator to 192.168.0.10:8010?
Moreover use 'ws' for 'http' and 'wss' for 'https'.

**Comment by Gregor193** [comment]
sorry, I tried this because I didn't know what function the json endpoint had. 
I chose a different address for the JSON endpoint because the instructions for the server said to avoid localhost. 

In the Config.json of the server, I have now also specified the address that I have stored in the JSON.endpoint. 

Do I need to do this in all places in config.json where localhost is noted? 

When starting the simulator, I now get the following feedback: 

![StationTemplates](https://user-images.githubusercontent.com/86152408/165066396-9a71174b-25fb-4553-89bc-4e4639ec75db.PNG)

However, I have copied the templates from the simulator into the specified path.

**Comment by Gregor193** [comment]
Please excuse the renewed request

When the token is created, default is entered for TenantID. This is indicated as invalid in the logs. 

Which entry in config.json generates the TenantID in the token or where do I have to make changes? 

Many thanks in advance
