### ISSUE TITLE
DC ChargingStation Settings 

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-dashboard#3102]
Hello together, 
the server and the dashboard are working. I have connected a DC charging station with 350KW. The plug type is CCS type 2. 900 volts and 500 amps are the maximum possible. 
Is there a possibility to change the configuration in the attached picture? 

![ChargingStationConfig](https://user-images.githubusercontent.com/86152408/166448128-a73aed6e-6baa-4fcd-a158-8dd2b78b9a76.PNG)

**Comment by LucasBrazi06** [comment]
> the server and the dashboard are working. I have connected a DC charging station with 350KW. The plug type is CCS type 2. 900 volts and 500 amps are the maximum possible.

As the DC Voltage/Amp are changing depending on the type of the battery (400V, 600V...) we cannot enter fixed DC values here.
For Smart Charging reason, we use here AC Power (Amps, Voltage) delivered by the grid to the charging station before the transformation to DC.
So if the voltage is 230, for your 350kW charging station, enter 507 A per phase (1521 A for 3 phases x 230 V = 349 830 W.)
This should do the trick.
Let me know.

**Comment by Gregor193** [comment]
have made the changes and the first loading tests look promising 
Many thanks for the support

**Comment by LucasBrazi06** [comment]
> have made the changes and the first loading tests look promising Many thanks for the support

You welcome ;-)
