### ISSUE TITLE
Graphical Bug/Overlay Dashboard

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-dashboard#3104]
Hello together, 
Since a short time I have a graphical overlay when calling up the dashboard via the browser. The problem exists with different browsers. Does anyone have any idea what is causing this and how I can fix it? 
Attached is a picture of the problem 
Thanks 

![IssueGraphicOverlay](https://user-images.githubusercontent.com/86152408/167350721-cecdcf4e-a082-45bd-91d2-91d35285b70f.PNG)

**Comment by LucasBrazi06** [comment]
This occurs only when you have no internet connection to download the icon pack.
