### ISSUE TITLE
import tags / users auto activation does not work

### ISSUE THREAD

**Issue by cabch** [sap-labs-france/ev-dashboard#3412]
as reported by @KinzaBS after client test

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI @Ramzay @cabch 
One remark: you should not have User or Tag references in a generic import pop-up.
If we import more entities in the future, this part will be a pain to maintain.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/25266945/196011290-84d8ce8e-ed97-4374-90c9-f7478c2c1046.png">

-> Use sub-component to display dedicated form controls for User and Tag according the entity type.
-> Type the dialog data Inject(MAT_DIALOG_DATA) data like in GeoMapDialogComponent and provide enums for data like 'entity'.
-> Increase also the button size which is cropped in french ;-).

That's it :-).
